"use client";
/* eslint-disable @next/next/no-img-element -- EIP-6963 icons are extension-provided data URLs. */

import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,type ReactNode} from "react";
import {failureDetails} from "@/lib/transactions";
import {resumeActivities} from "@/lib/activity";
import {BRADBURY_CHAIN_ID_HEX} from "@/lib/config";
import {bindProviderSession,connectionChoice,connectWalletCandidate,createConnectionGate,createWalletAccountGate,createWalletRefreshGate,discoverProviders,providerPresentationName,providerRegistry,readWalletSnapshot,safeProviderIcon,sessionEndMessages,walletRefreshStartBalance,type DiscoveryState,type Eip1193Provider,type ProviderDetail,type WalletAccountSnapshot,type WalletBalanceState,type WalletNetworkState,type SessionEndReason} from "@/lib/wallet";

type BalanceState={status:"idle"|WalletBalanceState["status"];value?:string};
type WalletState={account?:string;selected?:ProviderDetail;providers:ProviderDetail[];discoveryState:DiscoveryState;connect:()=>Promise<void>;select:(uuid:string)=>Promise<void>;disconnect:()=>void;switchWallet:()=>void;choosing:boolean;connectionPending:boolean;chooserError:string;sessionError:string;sessionStatus:string;networkState:WalletNetworkState;balance:BalanceState;closeChooser:()=>void};
const WalletContext=createContext<WalletState|null>(null);

export function WalletProvider({children}:{children:ReactNode}){
 const registry=useRef(providerRegistry()),gate=useRef(createConnectionGate()),accountGate=useRef(createWalletAccountGate()),refreshGate=useRef(createWalletRefreshGate()),sessionToken=useRef<number|undefined>(undefined),lastRefreshKey=useRef("");
 const chooser=useRef<HTMLDivElement>(null),restoreFocus=useRef<HTMLElement|null>(null),pendingRef=useRef(false);
 const [providers,setProviders]=useState<ProviderDetail[]>([]),[selected,setSelected]=useState<ProviderDetail>(),[account,setAccount]=useState<string>();
 const [choosing,setChoosing]=useState(false),[connectionPending,setConnectionPending]=useState(false),[chooserError,setChooserError]=useState(""),[sessionError,setSessionError]=useState("");
 const [sessionStatus,setSessionStatus]=useState("Wallet disconnected."),[networkState,setNetworkState]=useState<WalletNetworkState>("unavailable"),[balance,setBalance]=useState<BalanceState>({status:"idle"});
 const [discoveryState,setDiscoveryState]=useState<DiscoveryState>("DISCOVERING");

 const endSession=useCallback((reason:SessionEndReason="user")=>{const message=sessionEndMessages(reason);accountGate.current.clear();gate.current.invalidate();refreshGate.current.invalidate();lastRefreshKey.current="";sessionToken.current=undefined;setAccount(undefined);setSelected(undefined);setConnectionPending(false);setChooserError("");setChoosing(false);setNetworkState("unavailable");setBalance({status:"idle"});setSessionError(message.error);setSessionStatus(message.status)},[]);
 const closeChooser=useCallback(()=>{gate.current.invalidate();setConnectionPending(false);setChooserError("");setChoosing(false)},[]);
 const refresh=useCallback((detail:ProviderDetail)=>{registry.current.add(detail);setProviders(registry.current.list())},[]);
 const refreshNetworkAndBalance=useCallback(async(detail:ProviderDetail,accountSnapshot:WalletAccountSnapshot|undefined,token:number,force=false)=>{const nextAccount=accountSnapshot?.account??"",key=accountSnapshot?`${detail.info.uuid}:${accountSnapshot.generation}:${nextAccount.toLowerCase()}`:"";if(accountSnapshot&&!force&&lastRefreshKey.current===key)return;if(accountSnapshot)lastRefreshKey.current=key;const refreshToken=refreshGate.current.begin();setBalance(walletRefreshStartBalance(nextAccount));const snapshot=await readWalletSnapshot(detail.provider,nextAccount);const accountIsCurrent=accountSnapshot?accountGate.current.isCurrent(accountSnapshot):accountGate.current.current()===undefined;if(!refreshGate.current.isCurrent(refreshToken)||sessionToken.current!==token||!gate.current.isCurrent(token)||!accountIsCurrent)return;setNetworkState(snapshot.networkState);setBalance(snapshot.balance);if(snapshot.networkState==="changed"){setSessionError("Wallet network changed. Switch back to GenLayer Bradbury before making a transaction.");setSessionStatus("Wallet network changed from GenLayer Bradbury.")}else if(snapshot.networkState==="connected"&&accountSnapshot){setSessionError("");setSessionStatus(`Connected using ${providerPresentationName(detail.info.name)} on GenLayer Bradbury.`)}else if(snapshot.networkState==="connected"){setSessionError("Wallet account is unavailable. Reconnect to continue.");setSessionStatus("Wallet balance unavailable because no valid account is connected.")}else{setSessionError("Wallet network status is unavailable. Try again from your wallet.");setSessionStatus("Wallet network status unavailable.")}},[]);

 useEffect(()=>{const stop=discoverProviders(window,refresh);const timer=setTimeout(()=>{setProviders(registry.current.list());setDiscoveryState("COMPLETE")},250);return()=>{stop();clearTimeout(timer)}},[refresh]);
 useEffect(()=>{if(!selected||sessionToken.current===undefined)return;const token=sessionToken.current;return bindProviderSession(selected.provider,token,gate.current,{accountsChanged(next){if(next){const nextSnapshot=accountGate.current.set(next);if(!nextSnapshot){endSession("account");return}setAccount(nextSnapshot.account);lastRefreshKey.current="";setSessionError("");setSessionStatus("Wallet account changed. Refreshing network and balance.");void refreshNetworkAndBalance(selected,nextSnapshot,token,true)}else endSession("account")},chainChanged(chainId){lastRefreshKey.current="";const currentSnapshot=accountGate.current.snapshot();if(chainId&&chainId!==BRADBURY_CHAIN_ID_HEX){setNetworkState("changed");setBalance({status:"unavailable"});setSessionError("Wallet network changed. Switch back to GenLayer Bradbury before making a transaction.");setSessionStatus("Wallet network changed from GenLayer Bradbury.")}else setBalance(currentSnapshot?{status:"loading"}:{status:"unavailable"});void refreshNetworkAndBalance(selected,currentSnapshot,token,true)},disconnected(){endSession("provider")}})},[selected,endSession,refreshNetworkAndBalance]);
 useEffect(()=>{if(account)resumeActivities(window.localStorage,account)},[account]);
 useEffect(()=>{const currentSnapshot=accountGate.current.snapshot();if(account&&selected&&currentSnapshot&&currentSnapshot.account.toLowerCase()===account.toLowerCase()&&sessionToken.current!==undefined)void refreshNetworkAndBalance(selected,currentSnapshot,sessionToken.current)},[account,selected,refreshNetworkAndBalance]);
 useEffect(()=>{pendingRef.current=connectionPending;if(connectionPending&&choosing)chooser.current?.focus()},[connectionPending,choosing]);
 useEffect(()=>{if(!choosing)return;restoreFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;const dialog=chooser.current;const focusable=()=>[...(dialog?.querySelectorAll<HTMLElement>('button:not([disabled])')??[])];(focusable()[0]??dialog)?.focus();const keydown=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();if(!pendingRef.current)closeChooser();return}if(event.key!=="Tab")return;const items=focusable();if(items.length===0){event.preventDefault();dialog?.focus();return}const first=items[0],last=items[items.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){event.preventDefault();last.focus()}else if(!event.shiftKey&&(document.activeElement===last||document.activeElement===dialog)){event.preventDefault();first.focus()}};document.addEventListener("keydown",keydown);return()=>{document.removeEventListener("keydown",keydown);restoreFocus.current?.focus()}},[choosing,closeChooser]);

 const finish=useCallback(async(detail:ProviderDetail,inChooser:boolean)=>{accountGate.current.clear();const token=gate.current.begin();refreshGate.current.invalidate();lastRefreshKey.current="";setConnectionPending(true);setBalance({status:"loading"});setSessionStatus("Wallet connection request pending.");setChooserError("");setSessionError("");try{const nextAccount=await connectWalletCandidate(detail.provider);if(!gate.current.isCurrent(token))return;const nextSnapshot=accountGate.current.set(nextAccount);if(!nextSnapshot)throw new Error("Wallet returned no valid account");sessionToken.current=token;setSelected(detail);setAccount(nextSnapshot.account);setNetworkState("connected");setChoosing(false);void refreshNetworkAndBalance(detail,nextSnapshot,token,true)}catch(error){accountGate.current.clear();if(!gate.current.isCurrent(token))return;const failure=failureDetails(error,"NETWORK_VERIFICATION");const message=`${failure.message}${failure.providerCode!==undefined?` (provider code ${failure.providerCode})`:""}`;setBalance({status:"idle"});setSessionStatus("Wallet connection failed.");if(inChooser){setChooserError(message);setChoosing(true)}else setSessionError(message)}finally{if(gate.current.isCurrent(token))setConnectionPending(false)}},[refreshNetworkAndBalance]);
 const connect=useCallback(async()=>{try{const choice=connectionChoice(discoveryState,registry.current.list(),(window as Window&{ethereum?:Eip1193Provider}).ethereum);if(choice.kind==="discovering"){setSessionError("Injected-wallet discovery is still in progress.");return}if(choice.kind==="choose"){setChooserError("");setChoosing(true);return}if(choice.kind==="missing"){setSessionError("No injected wallet was found.");return}await finish(choice.detail,false)}catch(error){const failure=failureDetails(error,"CLIENT_INITIALIZATION");setSessionError(`${failure.message}${failure.providerCode!==undefined?` (provider code ${failure.providerCode})`:""}`)}},[discoveryState,finish]);
 const select=useCallback(async(uuid:string)=>{const detail=registry.current.get(uuid);if(!detail){setChooserError("Selected wallet provider is no longer available. Choose another provider.");return}await finish(detail,true)},[finish]);
 const switchWallet=useCallback(()=>{endSession("switch");setChooserError("");setChoosing(true);window.dispatchEvent(new Event("eip6963:requestProvider"))},[endSession]);
 const disconnect=useCallback(()=>endSession("user"),[endSession]);
 const value=useMemo(()=>({account,selected,providers,discoveryState,connect,select,disconnect,switchWallet,choosing,connectionPending,chooserError,sessionError,sessionStatus,networkState,balance,closeChooser}),[account,selected,providers,discoveryState,connect,select,disconnect,switchWallet,choosing,connectionPending,chooserError,sessionError,sessionStatus,networkState,balance,closeChooser]);

 return <WalletContext.Provider value={value}>{children}{choosing&&<div ref={chooser} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="wallet-dialog-title" aria-describedby="wallet-dialog-description" aria-busy={connectionPending} className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-5 outline-none"><div className="max-h-[calc(100vh-2.5rem)] w-full max-w-sm overflow-y-auto rounded-lg border border-white/15 bg-[#111827] p-5 shadow-2xl"><h2 id="wallet-dialog-title" className="text-lg font-semibold">Choose wallet</h2><p id="wallet-dialog-description" className="mt-2 text-xs text-white/55">Select an injected provider for this TruthMarket session. Switching does not revoke extension permissions or change Activity history.</p>{chooserError&&<p role="alert" className="mt-3 rounded border border-red-300/30 bg-red-300/10 p-3 text-sm text-red-100">{chooserError}</p>}<p role="status" aria-live="polite" className="mt-3 text-xs text-white/55">{connectionPending?"Connecting to the selected wallet. Approve or reject the request in the extension.":"Select one available injected wallet."}</p><div className="mt-4 grid gap-2">{providers.map(provider=>{const icon=safeProviderIcon(provider.info.icon),name=providerPresentationName(provider.info.name);return <button type="button" disabled={connectionPending} key={provider.info.uuid} onClick={()=>{void select(provider.info.uuid)}} className="flex min-h-12 min-w-0 items-center gap-3 rounded border border-white/15 p-3 text-left outline-none hover:bg-white/8 focus-visible:border-amber-300 focus-visible:ring-2 focus-visible:ring-amber-300/25 disabled:cursor-wait disabled:opacity-45">{icon?<img src={icon} alt="" className="size-7 shrink-0 rounded-md"/>:<span aria-hidden="true" className="grid size-7 shrink-0 place-items-center rounded bg-amber-300/10 text-xs text-amber-100">W</span>}<span className="min-w-0 truncate" title={name}>{name}</span></button>})}</div><button type="button" disabled={connectionPending} onClick={closeChooser} className="mt-4 rounded px-2 py-1 text-sm text-white/60 outline-none hover:text-white focus-visible:ring-2 focus-visible:ring-amber-300/40 disabled:cursor-wait disabled:opacity-45">Cancel</button></div></div>}</WalletContext.Provider>;
}

export function useWallet(){const value=useContext(WalletContext);if(!value)throw new Error("WalletProvider is missing");return value}
