"use client";

import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,type ReactNode} from "react";
import {failureDetails} from "@/lib/transactions";
import {resumeActivities} from "@/lib/activity";
import {bindProviderSession,connectionChoice,connectWalletCandidate,createConnectionGate,discoverProviders,providerRegistry,type DiscoveryState,type Eip1193Provider,type ProviderDetail} from "@/lib/wallet";

type WalletState={account?:string;selected?:ProviderDetail;providers:ProviderDetail[];discoveryState:DiscoveryState;connect:()=>Promise<void>;select:(uuid:string)=>Promise<void>;disconnect:()=>void;choosing:boolean;connectionPending:boolean;chooserError:string;sessionError:string;closeChooser:()=>void};
const WalletContext=createContext<WalletState|null>(null);

export function WalletProvider({children}:{children:ReactNode}){
 const registry=useRef(providerRegistry()),gate=useRef(createConnectionGate()),sessionToken=useRef<number|undefined>(undefined);
 const chooser=useRef<HTMLDivElement>(null),restoreFocus=useRef<HTMLElement|null>(null),pendingRef=useRef(false);
 const [providers,setProviders]=useState<ProviderDetail[]>([]),[selected,setSelected]=useState<ProviderDetail>(),[account,setAccount]=useState<string>();
 const [choosing,setChoosing]=useState(false),[connectionPending,setConnectionPending]=useState(false),[chooserError,setChooserError]=useState(""),[sessionError,setSessionError]=useState("");
 const [discoveryState,setDiscoveryState]=useState<DiscoveryState>("DISCOVERING");

 const endSession=useCallback((message="")=>{gate.current.invalidate();sessionToken.current=undefined;setAccount(undefined);setSelected(undefined);setConnectionPending(false);setChooserError("");setSessionError(message)},[]);
 const closeChooser=useCallback(()=>{gate.current.invalidate();setConnectionPending(false);setChooserError("");setChoosing(false)},[]);
 const refresh=useCallback((detail:ProviderDetail)=>{registry.current.add(detail);setProviders(registry.current.list())},[]);

 useEffect(()=>{const stop=discoverProviders(window,refresh);const timer=setTimeout(()=>{setProviders(registry.current.list());setDiscoveryState("COMPLETE")},250);return()=>{stop();clearTimeout(timer)}},[refresh]);
 useEffect(()=>{if(!selected||sessionToken.current===undefined)return;const token=sessionToken.current;return bindProviderSession(selected.provider,token,gate.current,{accountsChanged(next){if(next){setAccount(next);setSessionError("")}else endSession("The wallet no longer exposes an active account. Reconnect to continue.")},chainChanged(){setSessionError("The wallet network changed. Bradbury will be verified again before any write.")},disconnected(){endSession("The selected wallet provider disconnected or disappeared. Reconnect and select an available provider.")}})},[selected,endSession]);
 useEffect(()=>{if(account)resumeActivities(window.localStorage,account)},[account]);
 useEffect(()=>{pendingRef.current=connectionPending;if(connectionPending&&choosing)chooser.current?.focus()},[connectionPending,choosing]);
 useEffect(()=>{if(!choosing)return;restoreFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;const dialog=chooser.current;const focusable=()=>[...(dialog?.querySelectorAll<HTMLElement>('button:not([disabled])')??[])];(focusable()[0]??dialog)?.focus();const keydown=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();if(!pendingRef.current)closeChooser();return}if(event.key!=="Tab")return;const items=focusable();if(items.length===0){event.preventDefault();dialog?.focus();return}const first=items[0],last=items[items.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){event.preventDefault();last.focus()}else if(!event.shiftKey&&(document.activeElement===last||document.activeElement===dialog)){event.preventDefault();first.focus()}};document.addEventListener("keydown",keydown);return()=>{document.removeEventListener("keydown",keydown);restoreFocus.current?.focus()}},[choosing,closeChooser]);

 const finish=useCallback(async(detail:ProviderDetail,inChooser:boolean)=>{const token=gate.current.begin();setConnectionPending(true);setChooserError("");setSessionError("");try{const nextAccount=await connectWalletCandidate(detail.provider);if(!gate.current.isCurrent(token))return;sessionToken.current=token;setSelected(detail);setAccount(nextAccount);setChoosing(false)}catch(error){if(!gate.current.isCurrent(token))return;const failure=failureDetails(error,"NETWORK_VERIFICATION");const message=`${failure.message}${failure.providerCode!==undefined?` (provider code ${failure.providerCode})`:""}`;if(inChooser){setChooserError(message);setChoosing(true)}else setSessionError(message)}finally{if(gate.current.isCurrent(token))setConnectionPending(false)}},[]);
 const connect=useCallback(async()=>{try{const choice=connectionChoice(discoveryState,registry.current.list(),(window as Window&{ethereum?:Eip1193Provider}).ethereum);if(choice.kind==="discovering"){setSessionError("Injected-wallet discovery is still in progress.");return}if(choice.kind==="choose"){setChooserError("");setChoosing(true);return}if(choice.kind==="missing"){setSessionError("No injected wallet was found.");return}await finish(choice.detail,false)}catch(error){const failure=failureDetails(error,"CLIENT_INITIALIZATION");setSessionError(`${failure.message}${failure.providerCode!==undefined?` (provider code ${failure.providerCode})`:""}`)}},[discoveryState,finish]);
 const select=useCallback(async(uuid:string)=>{const detail=registry.current.get(uuid);if(!detail){setChooserError("Selected wallet provider is no longer available. Choose another provider.");return}await finish(detail,true)},[finish]);
 const value=useMemo(()=>({account,selected,providers,discoveryState,connect,select,disconnect:()=>endSession(),choosing,connectionPending,chooserError,sessionError,closeChooser}),[account,selected,providers,discoveryState,connect,select,endSession,choosing,connectionPending,chooserError,sessionError,closeChooser]);

 return <WalletContext.Provider value={value}>{children}{choosing&&<div ref={chooser} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="wallet-dialog-title" aria-describedby="wallet-dialog-description" aria-busy={connectionPending} className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-5 outline-none"><div className="w-full max-w-sm rounded-lg border border-white/15 bg-[#111827] p-5"><h2 id="wallet-dialog-title" className="text-lg font-semibold">Choose wallet</h2><p id="wallet-dialog-description" className="mt-2 text-xs text-white/55">TruthMarket will retain and use this exact provider for this app session. Disabled choices are waiting for the current connection attempt.</p>{chooserError&&<p role="alert" className="mt-3 rounded border border-red-300/30 bg-red-300/10 p-3 text-sm text-red-100">{chooserError}</p>}<p role="status" aria-live="polite" className="mt-3 text-xs text-white/55">{connectionPending?"Connecting to the selected wallet. Approve or reject the request in the extension.":"Select one available injected wallet."}</p><div className="mt-4 grid gap-2">{providers.map(provider=><button type="button" disabled={connectionPending} key={provider.info.uuid} onClick={()=>{void select(provider.info.uuid)}} className="border border-white/15 p-3 text-left hover:bg-white/8 disabled:cursor-wait disabled:opacity-45">{provider.info.name}</button>)}</div><button type="button" disabled={connectionPending} onClick={closeChooser} className="mt-4 text-sm text-white/60 disabled:cursor-wait disabled:opacity-45">Cancel</button></div></div>}</WalletContext.Provider>;
}

export function useWallet(){const value=useContext(WalletContext);if(!value)throw new Error("WalletProvider is missing");return value}
