import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
import ts from "typescript";
import {parseGen,formatGenWei} from "../lib/units.ts";
import {guardMarket,guardPosition,guardEvidenceList,guardResolution,guardChallenges,guardStats,guardLeaderboard,parseAndGuard} from "../lib/schemas.ts";
import {validateReadRequest,boundedRead,MAX_READ_ATTEMPTS} from "../lib/api-safety.ts";
import {bindProviderSession,connectionChoice,connectWalletCandidate,copyPublicAddress,createConnectionGate,createWalletAccountGate,createWalletRefreshGate,disclosureIsOpen,discoverProviders,formatNativeBalance,isWalletAddress,providerPresentationName,providerRegistry,readWalletSnapshot,safeProviderIcon,sessionEndMessages,ensureBradbury,shortenAddress,verifyWriteIdentity,walletExplorerUrl,walletNetworkStatusLabel,walletRefreshStartBalance,walletTriggerLabel} from "../lib/wallet.ts";
import {submitTransaction,resetSubmissionLockForTests,failureDetails,applySupplementaryRead,normalizeFailure,AppFailure} from "../lib/transactions.ts";
import {activityKey,activeMonitorCount,classifyReceipt,deriveProtocolState,deterministicActivityWinner,guardActivity,loadActivities,monitorActivity,persistActivity,reconcileStorageEvent,redactSecrets,resetActivityMonitorsForTests,resumeActivities,safeError,safeMessage} from "../lib/activity.ts";
import {BRADBURY_CHAIN_ID,TRUTHMARKET_CONTRACT_ADDRESS} from "../lib/config.ts";
import {findUniqueCreatedMarket,leaderboardPayout} from "../lib/post-checks.ts";

const exec=promisify(execFile);const address="0x1111111111111111111111111111111111111111";const hash=`0x${"a".repeat(64)}`;
const market={market_id:"1",creator:address,title:"A valid title",description:"A sufficiently descriptive claim",yes_rules:"yes",no_rules:"no",invalid_rules:"invalid",deadline:"2027-01-01T00:00:00Z",status:"OPEN",created_at:"2026-01-01T00:00:00Z",resolved_at:"",yes_pool:"0",no_pool:"0",invalid_pool:"0",total_pool:"0",evidence_count:"0",resolution_id:""};
function memoryStorage({fail=false}={}){const values=new Map();return{get length(){return values.size},key(i){return [...values.keys()][i]??null},getItem(k){return values.get(k)??null},setItem(k,v){if(fail)throw new Error("quota");values.set(k,v)},values}}
function activity(overrides={}){const now="2026-07-14T00:00:00.000Z";return{action:"Stake",contractMethod:"stake",marketId:"1",submittedAt:now,updatedAt:now,revision:0,transactionHash:hash,currentPhase:"submitted",terminal:false,pollingState:"IDLE",pollingStoppedAt:null,statusName:null,resultName:null,executionResult:null,safeError:null,supplementaryStateRead:null,chainId:BRADBURY_CHAIN_ID,contractAddress:TRUTHMARKET_CONTRACT_ADDRESS,walletAddress:address,...overrides}}
const receipt=(statusName,resultName="AGREE",txExecutionResultName="NOT_VOTED")=>({status:99,statusName,resultName,txExecutionResultName});

test("deadline formatting accepts ISO and Unix-seconds deadlines",async()=>{const source=await readFile("app/components/contract-data.tsx","utf8"),compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,loaded={exports:{}},require=id=>id==="@tanstack/react-query"?{useQuery(){}}:id==="@/lib/config"?{isContractConfigured(){return false}}:id==="@/lib/schemas"?{parseAndGuard(){}}:{};new Function("require","module","exports",compiled)(require,loaded,loaded.exports);for(const deadline of ["2027-01-01T00:00:00Z","1798761600"]){let formatted;assert.doesNotThrow(()=>{formatted=loaded.exports.formatDeadline(deadline)});assert.equal(typeof formatted,"string");assert.ok(formatted.length>0)}});

test("fixed GEN boundaries and unsafe syntax",()=>{assert.equal(parseGen("0"),0n);assert.equal(parseGen("0.000000000000000001"),1n);assert.equal(parseGen("1"),10n**18n);assert.equal(formatGenWei(10n**18n),"1 GEN");for(const value of ["","1e3","+1","-1","NaN","Infinity",".1","1.","0.0000000000000000001"])assert.throws(()=>parseGen(value),value)});
test("canonical market IDs and exact API args",()=>{assert.deepEqual(validateReadRequest({method:"get_market",args:["1"]}).args,["1"]);for(const id of ["0","01","-1","1.0",1])assert.throws(()=>validateReadRequest({method:"get_market",args:[id]}));assert.throws(()=>validateReadRequest({method:"get_stats",args:["1"]}));assert.throws(()=>validateReadRequest({method:"stake",args:[]}));assert.throws(()=>validateReadRequest({method:"get_market",args:["1"],extra:true}))});
test("exact V3 schemas and found variants",()=>{assert.equal(guardMarket(market).status,"OPEN");assert.throws(()=>guardMarket({...market,extra:1}));assert.throws(()=>guardMarket({...market,status:"UNKNOWN"}));assert.equal(guardPosition({market_id:"1",user:address,side:"",amount:"0",claimed:"false",found:false}).found,false);assert.deepEqual(guardEvidenceList([]),[]);assert.deepEqual(guardResolution({found:false}),{found:false});assert.deepEqual(guardChallenges([]),[]);assert.equal(guardStats({market_count:"0",finalized_count:"0",total_volume:"0"}).market_count,"0");assert.deepEqual(guardLeaderboard({[address]:"1"}),{[address]:"1"})});
test("JSON object/string parsing and HTML rejection",()=>{assert.equal(parseAndGuard("get_market",market).market_id,"1");assert.equal(parseAndGuard("get_market",JSON.stringify(market)).market_id,"1");assert.throws(()=>parseAndGuard("get_market","<!doctype html><h1>502</h1>"))});
test("API timeout makes one call and clears its timer",async()=>{assert.equal(MAX_READ_ATTEMPTS,1);let calls=0,cleared=0;const timer={set(fn){return setTimeout(fn,2)},clear(handle){cleared++;clearTimeout(handle)}};await assert.rejects(()=>boundedRead("get_market",["1"],()=>new Promise(()=>{calls++}),5,timer),/timed out/);assert.equal(calls,1);assert.equal(cleared,1)});
test("deterministic registry retains exact provider",()=>{const r=providerRegistry();const p={request:async()=>null};r.add({info:{uuid:"rabby",name:"Rabby",icon:"",rdns:"io.rabby"},provider:p});r.add({info:{uuid:"meta",name:"MetaMask",icon:"",rdns:"io.metamask"},provider:{request:async()=>null}});assert.equal(r.get("rabby").provider,p);assert.equal(r.list().length,2)});
test("switch first; add only on 4902; verify identity",async()=>{const calls=[];let first=true;const p={request:async({method,params})=>{calls.push([method,params]);if(method==="wallet_switchEthereumChain"&&first){first=false;throw {code:4902}}if(method==="eth_chainId")return "0x107d";if(method==="eth_accounts")return[address];return null}};await ensureBradbury(p);await verifyWriteIdentity(p,address);assert.deepEqual(calls.slice(0,3).map(x=>x[0]),["wallet_switchEthereumChain","wallet_addEthereumChain","wallet_switchEthereumChain"]);assert.equal(calls[1][1][0].nativeCurrency.decimals,18)});
test("candidate connection commits an account only after network and account steps succeed",async()=>{const calls=[];const provider={request:async({method})=>{calls.push(method);if(method==="eth_chainId")return"0x107d";if(method==="eth_requestAccounts")return[address];return null}};assert.equal(await connectWalletCandidate(provider),address);assert.deepEqual(calls,["wallet_switchEthereumChain","eth_chainId","eth_requestAccounts"]);await assert.rejects(()=>connectWalletCandidate({request:async({method})=>{if(method==="wallet_switchEthereumChain")throw {code:4001};return null}}));let first=true;await assert.rejects(()=>connectWalletCandidate({request:async({method})=>{if(method==="wallet_switchEthereumChain"&&first){first=false;throw {code:4902}}if(method==="wallet_addEthereumChain")throw {code:4001};return null}}));await assert.rejects(()=>connectWalletCandidate({request:async({method})=>{if(method==="eth_chainId")return"0x107d";if(method==="eth_requestAccounts")throw {code:4001};return null}}))});
test("session gate invalidates stale completion, validates chain events, and cleans listeners",()=>{const gate=createConnectionGate();const token=gate.begin();const handlers=new Map(),removed=[];const provider={request:async()=>null,on(event,handler){handlers.set(event,handler)},removeListener(event,handler){if(handlers.get(event)===handler)removed.push(event)}};let account,chainId,disconnects=0;const cleanup=bindProviderSession(provider,token,gate,{accountsChanged(value){account=value},chainChanged(value){chainId=value},disconnected(){disconnects++}});handlers.get("accountsChanged")([address]);handlers.get("chainChanged")("0X107D");assert.equal(account,address);assert.equal(chainId,"0x107d");handlers.get("chainChanged")({chainId:"0x1"});assert.equal(chainId,undefined);gate.invalidate();handlers.get("accountsChanged")(["0x2222222222222222222222222222222222222222"]);handlers.get("disconnect")();assert.equal(account,address);assert.equal(disconnects,0);cleanup();assert.deepEqual(removed.sort(),["accountsChanged","chainChanged","disconnect"].sort())});
test("wallet presentation and balance helpers cover bounded exact values",()=>{const unit=10n**18n;assert.equal(shortenAddress(address),"0x1111…1111");assert.equal(shortenAddress("short"),"short");assert.equal(walletExplorerUrl("https://explorer-bradbury.genlayer.com/",address),`https://explorer-bradbury.genlayer.com/address/${address}`);for(const [raw,expected] of [["0x0","0 GEN"],[`0x${unit.toString(16)}`,"1 GEN"],[`0x${(unit+2345n*10n**14n).toString(16)}`,"1.2345 GEN"],[`0x${(5n*10n**17n).toString(16)}`,"0.5 GEN"],[`0x${(1_000_000_000_000n*unit).toString(16)}`,"1,000,000,000,000 GEN"],[`0X${unit.toString(16).toUpperCase()}`,"1 GEN"]])assert.equal(formatNativeBalance(raw),expected);for(const raw of ["not-hex","0x",null,undefined])assert.equal(formatNativeBalance(raw),undefined)});
test("network snapshot supports Bradbury round trips, rejects invalid accounts, and contains RPC failures",async()=>{let chain="0x107d",balance=`0x${(2n*10n**18n).toString(16)}`;const calls=[];const provider={request:async({method,params})=>{calls.push([method,params]);if(method==="eth_chainId")return chain;if(method==="eth_getBalance")return balance;throw new Error("unexpected")}};assert.deepEqual(await readWalletSnapshot(provider,address),{networkState:"connected",balance:{status:"available",value:"2 GEN"}});for(const invalid of ["","0x1234","0x"+"g".repeat(40)]){assert.deepEqual(walletRefreshStartBalance(invalid),{status:"unavailable"});assert.deepEqual(await readWalletSnapshot(provider,invalid),{networkState:"connected",balance:{status:"unavailable"}})}assert.deepEqual(walletRefreshStartBalance(address),{status:"loading"});assert.equal(calls.filter(([method])=>method==="eth_getBalance").length,1);chain="0x1";assert.deepEqual(await readWalletSnapshot(provider,address),{networkState:"changed",balance:{status:"unavailable"}});chain="0x107d";balance=`0x${(3n*10n**18n).toString(16)}`;assert.deepEqual(await readWalletSnapshot(provider,address),{networkState:"connected",balance:{status:"available",value:"3 GEN"}});assert.deepEqual(calls.filter(([method])=>method==="eth_getBalance").map(([,params])=>params),[[address,"latest"],[address,"latest"]]);assert.equal(isWalletAddress(address),true);assert.equal(isWalletAddress(""),false);assert.deepEqual(await readWalletSnapshot({request:async()=>{throw new Error("private RPC detail")}},address),{networkState:"unavailable",balance:{status:"unavailable"}});assert.deepEqual(await readWalletSnapshot({request:async({method})=>method==="eth_chainId"?"0x107d":Promise.reject(new Error("balance rejected"))},address),{networkState:"connected",balance:{status:"unavailable"}})});
test("refresh gate rejects old-account and post-disconnect balance results",async()=>{const gate=createWalletRefreshGate();let visible="none",releaseOld;const old=new Promise(resolve=>{releaseOld=resolve}),oldToken=gate.begin();const oldCommit=old.then(value=>{if(gate.isCurrent(oldToken))visible=value});const newToken=gate.begin();visible="new account";releaseOld("old account");await oldCommit;assert.equal(visible,"new account");assert.equal(gate.isCurrent(newToken),true);let releaseDisconnected;const pending=new Promise(resolve=>{releaseDisconnected=resolve}),pendingToken=gate.begin();const disconnectedCommit=pending.then(value=>{if(gate.isCurrent(pendingToken))visible=value});gate.invalidate();visible="disconnected";releaseDisconnected("stale balance");await disconnectedCommit;assert.equal(visible,"disconnected")});
test("account identity gate closes accountsChanged then chainChanged publication race",async()=>{const accounts=createWalletAccountGate(),refreshes=createWalletRefreshGate(),a=accounts.set(address);assert.ok(a);let published="",releaseA;const pendingA=new Promise(resolve=>{releaseA=resolve}),start=async(snapshot,value,pending=Promise.resolve())=>{const refresh=refreshes.begin();await pending;if(refreshes.isCurrent(refresh)&&accounts.isCurrent(snapshot))published=value};const oldA=start(a,"A",pendingA);const bAddress="0x2222222222222222222222222222222222222222",b=accounts.set(bAddress);assert.ok(b);assert.equal(accounts.isCurrent(a),false);const accountRefresh=start(b,"B account"),chainSnapshot=accounts.snapshot();assert.equal(chainSnapshot.account,bAddress);const chainRefresh=start(chainSnapshot,"B chain");await Promise.all([accountRefresh,chainRefresh]);assert.equal(published,"B chain");releaseA();await oldA;assert.equal(published,"B chain");const upper=accounts.set(bAddress.toUpperCase().replace("0X","0x"));assert.ok(upper);assert.equal(accounts.current().toLowerCase(),bAddress);assert.equal(accounts.isCurrent(b),false);assert.equal(accounts.isCurrent(upper),true);assert.equal(accounts.set("bad"),undefined);assert.equal(accounts.current().toLowerCase(),bAddress);accounts.clear();assert.equal(accounts.isCurrent(upper),false);assert.equal(accounts.current(),undefined);const reconnect=accounts.set(address);assert.ok(reconnect);accounts.clear();assert.equal(accounts.isCurrent(reconnect),false)});
test("provider icons, labels, names, clipboard, disclosure, and session messages are safely bounded",async()=>{const icon="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAB";assert.equal(safeProviderIcon(icon),icon);for(const value of ["https://tracker.test/icon.png","http://tracker.test/icon.png","javascript:alert(1)","blob:x","file:///x","data:image/svg+xml;base64,PHN2Zz4=","data:image/gif;base64,R0lGODlhAQ==","data:image/png;base64,QUFBQUFBQUFBQUFB","data:image/png;base64,***",`data:image/png;base64,${"A".repeat(100_004)}`,null])assert.equal(safeProviderIcon(value),undefined);assert.equal(providerPresentationName("X".repeat(100)).length,48);assert.equal(providerPresentationName("\u0000 Rab\u0085by\u009f "),"Rabby");assert.equal(providerPresentationName("\u0085\u009f"),"Injected wallet");assert.match(walletTriggerLabel(address,"Rabby","connected"),/on GenLayer Bradbury$/);assert.match(walletTriggerLabel(address,"Rabby","changed"),/network changed from GenLayer Bradbury$/);assert.deepEqual([walletNetworkStatusLabel("connected"),walletNetworkStatusLabel("changed"),walletNetworkStatusLabel("unavailable")],["Connected on Bradbury","Wallet network changed","Network status unavailable"]);assert.equal(disclosureIsOpen(address,address,true),true);assert.equal(disclosureIsOpen(address,undefined,true),false);assert.equal(disclosureIsOpen(address,"0x2222222222222222222222222222222222222222",true),false);assert.equal(disclosureIsOpen(undefined,address,true),false);let copied="";assert.equal(await copyPublicAddress(address,async value=>{copied=value}),"copied");assert.equal(copied,address);assert.equal(await copyPublicAddress(address,async()=>{throw new Error("denied")}),"unavailable");assert.equal(sessionEndMessages("user").error,"");assert.match(sessionEndMessages("user").status,/permissions were not changed/);assert.match(sessionEndMessages("provider").error,/disconnected or disappeared/)});
test("connected wallet disclosure exposes actions and coherent accessibility structure",async()=>{const chrome=await readFile("app/components/chrome.tsx","utf8");for(const expected of ["Copy address","Copy unavailable — select and copy the address manually","View on Bradbury explorer","Switch wallet","Disconnect","Required network","Required chain ID","aria-expanded={open}","aria-controls=\"connected-wallet-popup\"","id=\"connected-wallet-popup\"","event.key===\"Escape\"","pointerdown","noopener noreferrer","data-wallet-action"])assert.ok(chrome.includes(expected),expected);assert.doesNotMatch(chrome,/role="menu(?:item)?"/);assert.match(chrome,/setDisclosure\(\{owner:account,open:!open\}\)/);assert.match(chrome,/requestAnimationFrame\(\(\)=>triggerRef\.current\?\.focus\(\)\)/)});
test("switch and disconnect reset session without touching Activity or permissions",async()=>{const source=await readFile("app/components/wallet-provider.tsx","utf8");assert.match(source,/switchWallet=useCallback\(\(\)=>\{endSession\("switch"\).*setChoosing\(true\).*eip6963:requestProvider/s);assert.match(source,/gate\.current\.invalidate\(\).*setAccount\(undefined\).*setSelected\(undefined\)/s);assert.match(source,/refreshGate\.current\.invalidate\(\)/);assert.match(source,/return bindProviderSession/);assert.doesNotMatch(source,/localStorage\.(?:clear|removeItem)/);assert.doesNotMatch(source,/wallet_revokePermissions/)});

test("SDK-shaped receipt classification has explicit terminal precedence",()=>{const cases=[
 [receipt("FINALIZED","AGREE","FINISHED_WITH_RETURN"),"finalized success",true],
 [receipt("FINALIZED","AGREE","FINISHED_WITH_ERROR"),"execution failure",true],
 [receipt("ACCEPTED"),"confirmation/accepted",false],[receipt("READY_TO_FINALIZE"),"ready to finalize",false],
 [receipt("CANCELED"),"canceled",true],[receipt("VALIDATORS_TIMEOUT"),"timeout",true],[receipt("LEADER_TIMEOUT"),"timeout",true],
 [receipt("UNDETERMINED","TIMEOUT"),"timeout",true],[receipt("UNDETERMINED","NO_MAJORITY"),"no majority",true],[receipt("UNDETERMINED","DISAGREE"),"disagreement/failure",true],
 [receipt("UNDETERMINED","MAJORITY_DISAGREE"),"disagreement/failure",true],[receipt("UNDETERMINED","DETERMINISTIC_VIOLATION"),"disagreement/failure",true]
 ];for(const [input,phase,terminal] of cases){const result=classifyReceipt(input);assert.equal(result.currentPhase,phase);assert.equal(result.terminal,terminal)}});
test("unknown normalized receipt fields remain retryable and nonterminal",()=>{const result=classifyReceipt({status:999,statusName:"FUTURE_STATUS",resultName:undefined,txExecutionResultName:undefined});assert.equal(result.currentPhase,"retryable unknown polling error");assert.equal(result.terminal,false)});
test("every recognized SDK status has one canonical stored protocol state",()=>{const cases=[
 ["UNINITIALIZED","IDLE","NOT_VOTED","submitted",false],["PENDING","IDLE","NOT_VOTED","submitted",false],["PROPOSING","AGREE","NOT_VOTED","submitted",false],["COMMITTING","MAJORITY_AGREE","NOT_VOTED","submitted",false],["REVEALING","IDLE",null,"submitted",false],["APPEAL_REVEALING","IDLE","NOT_VOTED","submitted",false],["APPEAL_COMMITTING","IDLE","NOT_VOTED","submitted",false],
 ["ACCEPTED","AGREE","NOT_VOTED","confirmation/accepted",false],["READY_TO_FINALIZE","MAJORITY_AGREE","NOT_VOTED","ready to finalize",false],["UNDETERMINED","AGREE","NOT_VOTED","undetermined",false],
 ["UNDETERMINED","TIMEOUT","NOT_VOTED","timeout",true],["UNDETERMINED","NO_MAJORITY","NOT_VOTED","no majority",true],["UNDETERMINED","DISAGREE","NOT_VOTED","disagreement/failure",true],["UNDETERMINED","MAJORITY_DISAGREE","NOT_VOTED","disagreement/failure",true],["UNDETERMINED","DETERMINISTIC_VIOLATION","NOT_VOTED","disagreement/failure",true],
 ["FINALIZED","AGREE","FINISHED_WITH_RETURN","finalized success",true],["FINALIZED","AGREE","FINISHED_WITH_ERROR","execution failure",true],["FINALIZED","AGREE","NOT_VOTED","execution failure",true],["FINALIZED","AGREE",null,"execution failure",true],["CANCELED","IDLE","NOT_VOTED","canceled",true],["VALIDATORS_TIMEOUT","TIMEOUT","NOT_VOTED","timeout",true],["LEADER_TIMEOUT","TIMEOUT","NOT_VOTED","timeout",true]
 ];for(const [statusName,resultName,txExecutionResultName,phase,terminal] of cases){const classified=classifyReceipt({statusName,resultName,txExecutionResultName});assert.equal(classified.currentPhase,phase,statusName);assert.equal(classified.terminal,terminal,statusName);const stored=activity({...classified,pollingState:terminal?"TERMINAL":"ACTIVE",pollingStoppedAt:null});assert.ok(guardActivity(stored),`${statusName}/${resultName}/${txExecutionResultName}`);const derived=deriveProtocolState({statusName,resultName,executionResult:txExecutionResultName});assert.equal(derived?.phase,phase);assert.equal(derived?.terminal,terminal)}});
test("local submission and polling-error exceptions remain coherent",()=>{for(const pollingState of ["IDLE","ACTIVE"]){assert.ok(guardActivity(activity({pollingState})))}assert.ok(guardActivity(activity({pollingState:"PAUSED",pollingStoppedAt:"2026-07-14T00:01:00.000Z"})));assert.ok(guardActivity(activity({currentPhase:"retryable unknown polling error",pollingState:"ACTIVE",safeError:{stage:"POLLING",message:"temporary"}})))});
test("inverse finality matrix rejects every contradictory stored combination",()=>{const stopped="2026-07-14T00:01:00.000Z";const bad=[
 {currentPhase:"submitted",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"},{currentPhase:"undetermined",statusName:"ACCEPTED"},{currentPhase:"submitted",statusName:"CANCELED"},{currentPhase:"canceled",terminal:true,pollingState:"TERMINAL",statusName:"CANCELED",executionResult:"FINISHED_WITH_RETURN"},
 {currentPhase:"confirmation/accepted",statusName:"READY_TO_FINALIZE"},{currentPhase:"ready to finalize",statusName:"ACCEPTED"},{currentPhase:"finalized success",terminal:true,pollingState:"TERMINAL",statusName:"FINALIZED",executionResult:"FINISHED_WITH_ERROR"},{currentPhase:"execution failure",terminal:true,pollingState:"TERMINAL",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"},
 {currentPhase:"submitted",terminal:false,pollingState:"TERMINAL"},{currentPhase:"finalized success",terminal:true,pollingState:"ACTIVE",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"},{currentPhase:"finalized success",terminal:true,pollingState:"PAUSED",pollingStoppedAt:stopped,statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"},{currentPhase:"finalized success",terminal:true,pollingState:"IDLE",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"},
 {currentPhase:"submitted",statusName:"PENDING",resultName:"IDLE",executionResult:"FINISHED_WITH_RETURN"},{currentPhase:"timeout",terminal:true,pollingState:"TERMINAL",statusName:"ACCEPTED",resultName:"TIMEOUT"},{currentPhase:"no majority",terminal:true,pollingState:"TERMINAL",statusName:"UNDETERMINED",resultName:"AGREE"},{currentPhase:"disagreement/failure",terminal:true,pollingState:"TERMINAL",statusName:"UNDETERMINED",resultName:"AGREE"},
 {pollingState:"PAUSED",pollingStoppedAt:null},{pollingState:"ACTIVE",pollingStoppedAt:stopped},{pollingState:"IDLE",pollingStoppedAt:stopped},{currentPhase:"finalized success",terminal:true,pollingState:"TERMINAL",pollingStoppedAt:stopped,statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"},{currentPhase:"finalized success",terminal:true,pollingState:"TERMINAL",statusName:null,resultName:null,executionResult:null},{currentPhase:"finalized success",terminal:true,pollingState:"TERMINAL",statusName:"FUTURE_STATUS",executionResult:"FINISHED_WITH_RETURN"}
 ];for(const patch of bad)assert.equal(guardActivity(activity(patch)),null,JSON.stringify(patch))});
test("contradictory receipt candidates receive a safe warning and never enter the journal",async()=>{const storage=memoryStorage(),candidate=activity({currentPhase:"submitted",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"}),result=await persistActivity(storage,candidate,{locks:null});assert.equal(result.written,false);assert.equal(result.warning.stage,"STORAGE");assert.equal(storage.length,0)});
test("monitor persists ACTIVE, ACCEPTED, READY_TO_FINALIZE, and terminal success",async()=>{resetActivityMonitorsForTests();const storage=memoryStorage();const states=[receipt("ACCEPTED"),receipt("READY_TO_FINALIZE"),receipt("FINALIZED","AGREE","FINISHED_WITH_RETURN")];const seen=[];const original=storage.setItem.bind(storage);storage.setItem=(k,v)=>{original(k,v);seen.push(JSON.parse(v).currentPhase)};const result=await monitorActivity(activity(),{storage,getTransaction:async()=>states.shift(),sleep:async()=>{},maxPolls:3});assert.deepEqual(seen,["submitted","confirmation/accepted","ready to finalize","finalized success"]);assert.equal(result.pollingState,"TERMINAL");assert.equal(result.terminal,true)});
test("transient polling errors preserve stronger accepted state",async()=>{const storage=memoryStorage();let n=0;const result=await monitorActivity(activity(),{storage,getTransaction:async()=>{n++;if(n===1)return receipt("ACCEPTED");if(n===2)throw {code:503,message:"temporary"};return receipt("FINALIZED","AGREE","FINISHED_WITH_RETURN")},sleep:async()=>{},maxPolls:3});assert.equal(result.currentPhase,"finalized success");const revisions=[...storage.values.values()].map(JSON.parse);assert.equal(revisions.at(-1).terminal,true)});
test("bounded exhaustion pauses while preserving ACCEPTED and manual retry polls only",async()=>{const storage=memoryStorage();let reads=0,writes=0;const accepted=await monitorActivity(activity(),{storage,getTransaction:async()=>{reads++;return receipt("ACCEPTED")},sleep:async()=>{},maxPolls:1});assert.equal(accepted.currentPhase,"confirmation/accepted");assert.equal(accepted.pollingState,"PAUSED");assert.match(accepted.safeError.message,/polling window ended/i);assert.ok(accepted.pollingStoppedAt);const resumed=await monitorActivity(accepted,{storage,getTransaction:async()=>{reads++;return receipt("READY_TO_FINALIZE")},sleep:async()=>{},maxPolls:1});assert.equal(resumed.currentPhase,"ready to finalize");assert.equal(resumed.pollingState,"PAUSED");assert.equal(reads,2);assert.equal(writes,0)});
test("terminal Activity is never resumed",async()=>{const storage=memoryStorage();const terminal=activity({terminal:true,pollingState:"TERMINAL",currentPhase:"finalized success",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"});await persistActivity(storage,terminal);let reads=0;assert.equal(resumeActivities(storage,address,{getTransaction:async()=>{reads++;return receipt("FINALIZED","AGREE","FINISHED_WITH_RETURN")}}),0);assert.equal(reads,0)});
test("durable Activity guard ignores malformed and wrong namespace records",()=>{assert.ok(guardActivity(activity()));for(const bad of [{...activity(),revision:-1},{...activity(),transactionHash:"bad"},{...activity(),walletAddress:"bad"},{...activity(),chainId:1},{...activity(),extra:true}])assert.equal(guardActivity(bad),null);const storage=memoryStorage();storage.values.set(activityKey(address,hash),"not json");storage.values.set(activityKey(address,`0x${"b".repeat(64)}`),JSON.stringify({...activity({transactionHash:`0x${"b".repeat(64)}`}),chainId:1}));assert.deepEqual(loadActivities(storage,address),[])});
test("monotonic persistence permanently preserves terminal state",async()=>{const storage=memoryStorage();const terminal=(await persistActivity(storage,activity({currentPhase:"execution failure",terminal:true,pollingState:"TERMINAL",statusName:"FINALIZED",executionResult:"FINISHED_WITH_ERROR"}))).activity;const regressed=(await persistActivity(storage,activity({revision:0,currentPhase:"submitted",terminal:false}))).activity;assert.equal(regressed.currentPhase,"execution failure");assert.equal(storage.length,2);const conflicting=(await persistActivity(storage,activity({revision:terminal.revision,currentPhase:"finalized success",terminal:true,pollingState:"TERMINAL",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"}))).activity;assert.equal(conflicting.currentPhase,"finalized success")});
test("deterministic conflict precedence is independent of invocation order",()=>{const success=activity({terminal:true,pollingState:"TERMINAL",currentPhase:"finalized success",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"});const failure=activity({terminal:true,pollingState:"TERMINAL",currentPhase:"execution failure",statusName:"FINALIZED",executionResult:"FINISHED_WITH_ERROR"});const accepted=activity({currentPhase:"confirmation/accepted",statusName:"ACCEPTED"});const polling=activity({currentPhase:"retryable unknown polling error",safeError:{stage:"POLLING",message:"temporary"}});assert.equal(deterministicActivityWinner(success,failure).currentPhase,"finalized success");assert.equal(deterministicActivityWinner(failure,success).currentPhase,"finalized success");assert.equal(deterministicActivityWinner(accepted,polling).currentPhase,"confirmation/accepted");assert.equal(deterministicActivityWinner(polling,accepted).currentPhase,"confirmation/accepted")});
test("Web Locks serialize the complete persistence critical section",async()=>{const storage=memoryStorage();let tail=Promise.resolve(),active=0,maxActive=0,calls=0;const locks={request(_name,callback){calls++;const run=tail.then(async()=>{active++;maxActive=Math.max(maxActive,active);await new Promise(resolve=>setTimeout(resolve,1));try{return await callback()}finally{active--}});tail=run.catch(()=>{});return run}};const submitted=activity();const success=activity({terminal:true,pollingState:"TERMINAL",currentPhase:"finalized success",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"});await Promise.all([persistActivity(storage,submitted,{locks}),persistActivity(storage,success,{locks})]);assert.equal(calls,2);assert.equal(maxActive,1);assert.equal(loadActivities(storage,address)[0].currentPhase,"finalized success")});
test("fallback reread preserves a concurrently observed stronger record",async()=>{const storage=memoryStorage();const strong=activity({revision:4,currentPhase:"ready to finalize",statusName:"READY_TO_FINALIZE"});let injected=false;const original=storage.setItem.bind(storage);storage.setItem=(key,value)=>{original(key,value);if(!injected){injected=true;original(key,JSON.stringify(strong))}};const result=await persistActivity(storage,activity(),{locks:null,fallbackAttempts:2});assert.equal(result.activity.currentPhase,"ready to finalize")});
test("storage-event reconciliation validates namespace and payload",async()=>{const storage=memoryStorage();const a=(await persistActivity(storage,activity())).activity;const key=activityKey(address,hash);assert.equal(reconcileStorageEvent(storage,address,{key,newValue:JSON.stringify(a)}).transactionHash,hash);assert.equal(reconcileStorageEvent(storage,address,{key:"other",newValue:JSON.stringify(a)}),null);assert.equal(reconcileStorageEvent(storage,address,{key,newValue:"{}"}),null)});
test("reload recovery polls without transaction submission and suppresses duplicate monitors",async()=>{resetActivityMonitorsForTests();const storage=memoryStorage();await persistActivity(storage,activity());let reads=0;let release;const gate=new Promise(resolve=>{release=resolve});const options={getTransaction:async()=>{reads++;await gate;return receipt("FINALIZED","AGREE","FINISHED_WITH_RETURN")},sleep:async()=>{},maxPolls:1};assert.equal(resumeActivities(storage,address,options),1);assert.equal(resumeActivities(storage,address,options),1);assert.equal(activeMonitorCount(),1);release();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(reads,1);assert.equal(activeMonitorCount(),0);assert.equal(loadActivities(storage,address)[0].terminal,true)});

test("uncontended no-lock journal persistence succeeds without warning",async()=>{const storage=memoryStorage();const result=await persistActivity(storage,activity(),{locks:null});assert.equal(result.written,true);assert.equal(result.warning,null);assert.equal(result.activity.currentPhase,"submitted");assert.equal(storage.length,1)});
test("journal entries are immutable and derive the strongest state independent of order",async()=>{for(const reverse of [false,true]){const storage=memoryStorage();const weak=activity(),strong=activity({currentPhase:"finalized success",terminal:true,pollingState:"TERMINAL",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"});for(const item of reverse?[strong,weak]:[weak,strong])await persistActivity(storage,item,{locks:null});assert.equal(storage.length,2);assert.equal(loadActivities(storage,address)[0].currentPhase,"finalized success")}});
test("journal key namespace is bound to the complete Activity record",()=>{const event="12345678-1234-4123-8123-123456789abc",otherHash=`0x${"b".repeat(64)}`,otherWallet="0x2222222222222222222222222222222222222222";for(const [key,record] of [[activityKey(address,hash,event),activity({transactionHash:otherHash})],[activityKey(otherWallet,hash,event),activity()],[`truthmarket:activity-event:1:${TRUTHMARKET_CONTRACT_ADDRESS.toLowerCase()}:${address}:${hash}:${event}`,activity()],[`truthmarket:activity-event:${BRADBURY_CHAIN_ID}:0x2222222222222222222222222222222222222222:${address}:${hash}:${event}`,activity()],[activityKey(address,hash,"bad"),activity()],[`${activityKey(address,hash,event)}:extra`,activity()]]){const storage=memoryStorage();storage.values.set(key,JSON.stringify(record));assert.deepEqual(loadActivities(storage,address),[])}});
test("exact finality and polling timestamp invariants reject contradictions",()=>{const invalid=[activity({currentPhase:"finalized success",terminal:true,pollingState:"TERMINAL",statusName:"ACCEPTED",executionResult:"FINISHED_WITH_RETURN"}),activity({currentPhase:"execution failure",terminal:true,pollingState:"TERMINAL",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"}),activity({pollingState:"PAUSED",pollingStoppedAt:null}),activity({pollingState:"ACTIVE",pollingStoppedAt:"2026-07-14T00:00:00.000Z"}),activity({pollingState:"IDLE",pollingStoppedAt:"2026-07-14T00:00:00.000Z"})];for(const item of invalid)assert.equal(guardActivity(item),null)});
test("action is fixed by contract method",()=>{assert.ok(guardActivity(activity()));assert.equal(guardActivity(activity({action:"stake"})),null);assert.equal(guardActivity(activity({action:"x".repeat(10000)})),null)});
test("malformed candidates cannot defeat valid history",async()=>{const valid=activity({currentPhase:"confirmation/accepted",statusName:"ACCEPTED"}),malformed=activity({action:"forged"});assert.equal(deterministicActivityWinner(valid,malformed).currentPhase,"confirmation/accepted");const storage=memoryStorage();await persistActivity(storage,valid,{locks:null});const rejected=await persistActivity(storage,malformed,{locks:null});assert.equal(rejected.written,false);assert.equal(loadActivities(storage,address)[0].currentPhase,"confirmation/accepted")});
test("direct terminal monitor returns without persistence or polling",async()=>{const storage=memoryStorage();let reads=0;const terminal=activity({currentPhase:"finalized success",terminal:true,pollingState:"TERMINAL",statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"});const result=await monitorActivity(terminal,{storage,getTransaction:async()=>{reads++;throw new Error("must not run")}});assert.equal(result,terminal);assert.equal(reads,0);assert.equal(storage.length,0)});
test("duplicate monitor contains hostile storage reads",async()=>{resetActivityMonitorsForTests();let release;const pending=new Promise(resolve=>{release=resolve}),storage={get length(){throw new Error("blocked")},key(){throw new Error("blocked")},getItem(){throw new Error("blocked")},setItem(){throw new Error("blocked")}};const options={storage,monitorLocks:null,getTransaction:async()=>{await pending;return receipt("FINALIZED","AGREE","FINISHED_WITH_RETURN")},maxPolls:1};const first=monitorActivity(activity(),options);await new Promise(resolve=>setTimeout(resolve,0));await assert.doesNotReject(()=>monitorActivity(activity(),options));release();await first});
test("monitor Web Lock ownership is requested non-blockingly",async()=>{const storage=memoryStorage();let reads=0,optionsSeen;const locks={request(_name,options,callback){optionsSeen=options;return Promise.resolve(callback(null))}};const result=await monitorActivity(activity(),{storage,monitorLocks:locks,getTransaction:async()=>{reads++;return receipt("FINALIZED","AGREE","FINISHED_WITH_RETURN")}});assert.equal(optionsSeen.ifAvailable,true);assert.equal(reads,0);assert.equal(result.currentPhase,"submitted")});
test("storage reconciliation never starts or resumes polling",async()=>{resetActivityMonitorsForTests();const storage=memoryStorage();const paused=activity({currentPhase:"confirmation/accepted",statusName:"ACCEPTED",pollingState:"PAUSED",pollingStoppedAt:"2026-07-14T00:01:00.000Z",safeError:{stage:"POLLING",message:"paused"}});const persisted=await persistActivity(storage,paused,{locks:null});const key=[...storage.values.keys()][0];assert.equal(reconcileStorageEvent(storage,address,{key,newValue:JSON.stringify(persisted.activity)}).pollingState,"PAUSED");assert.equal(activeMonitorCount(),0)});
test("EIP-6963 discovery gates fallback and deterministically chooses",()=>{const fallback={request:async()=>null},one={info:{uuid:"one",name:"One",icon:"",rdns:"one"},provider:{request:async()=>null}},two={info:{uuid:"two",name:"Two",icon:"",rdns:"two"},provider:{request:async()=>null}};assert.equal(connectionChoice("DISCOVERING",[],fallback).kind,"discovering");assert.equal(connectionChoice("COMPLETE",[one],fallback).detail,one);assert.equal(connectionChoice("COMPLETE",[one,two],fallback).kind,"choose");assert.equal(connectionChoice("COMPLETE",[],fallback).detail.provider,fallback);const chosen=connectionChoice("COMPLETE",[],fallback).detail;assert.equal(connectionChoice("COMPLETE",[one],fallback).detail,one);assert.notEqual(chosen.provider,one.provider)});
test("EIP-6963 request and announcement bind the announced provider",()=>{const target=new EventTarget(),provider={request:async()=>null},detail={info:{uuid:"announced",name:"Announced",icon:"",rdns:"wallet.test"},provider};target.addEventListener("eip6963:requestProvider",()=>{const event=new Event("eip6963:announceProvider");Object.defineProperty(event,"detail",{value:detail});target.dispatchEvent(event)});let observed;const stop=discoverProviders(target,value=>{observed=value});assert.equal(observed,detail);assert.equal(observed.provider,provider);stop()});

test("pipeline uses exact provider, verifies identity, and persists only valid hash",async()=>{resetSubmissionLockForTests();const calls=[];const storage=memoryStorage();const p={request:async({method})=>{calls.push(method);return method==="eth_chainId"?"0x107d":method==="eth_accounts"?[address]:null}};const stages=[];const result=await submitTransaction({account:address,provider:p,action:"stake",method:"stake",args:["1","YES"],value:1n,storage,onStage:s=>stages.push(s),write:async o=>{assert.equal(o.provider,p);assert.deepEqual(calls.slice(-2),["eth_chainId","eth_accounts"]);assert.equal(o.value,1n);return hash}});assert.equal(result.transactionHash,hash);assert.equal(storage.length,1);assert.deepEqual(stages,["PREPARATION","CLIENT_INITIALIZATION","NETWORK_VERIFICATION","WALLET_SUBMISSION","HASH_VALIDATION"]);await assert.rejects(()=>submitTransaction({account:address,provider:p,action:"stake",method:"stake",storage,write:async()=>"bad"}));assert.equal(storage.length,1)});
test("valid hash survives browser storage failure without resubmission invitation",async()=>{resetSubmissionLockForTests();let writes=0;const p={request:async({method})=>method==="eth_chainId"?"0x107d":method==="eth_accounts"?[address]:null};const result=await submitTransaction({account:address,provider:p,action:"stake",method:"stake",storage:memoryStorage({fail:true}),write:async()=>{writes++;return hash}});assert.equal(result.transactionHash,hash);assert.equal(result.storageWarning.stage,"STORAGE");assert.equal(writes,1)});
test("valid hash also survives browser storage read failure",async()=>{resetSubmissionLockForTests();const p={request:async({method})=>method==="eth_chainId"?"0x107d":method==="eth_accounts"?[address]:null};const storage={length:0,key(){return null},getItem(){throw new Error("blocked")},setItem(){throw new Error("blocked")}};const result=await submitTransaction({account:address,provider:p,action:"stake",method:"stake",storage,write:async()=>hash});assert.equal(result.transactionHash,hash);assert.equal(result.storageWarning.stage,"STORAGE")});
test("synchronous duplicate lock",async()=>{resetSubmissionLockForTests();let release;const gate=new Promise(r=>release=r);const p={request:async({method})=>method==="eth_chainId"?"0x107d":[address]};const first=submitTransaction({account:address,provider:p,action:"x",method:"resolve_market",write:async()=>{await gate;return hash}});await new Promise(r=>setTimeout(r,0));await assert.rejects(()=>submitTransaction({account:address,provider:p,action:"x",method:"resolve_market"}),e=>failureDetails(e).stage==="PREPARATION");release();await first});
test("forged stages are ignored and secrets are deeply normalized",()=>{const forged=failureDetails({stage:"HASH_VALIDATION",code:4001,message:"user rejected"},"WALLET_SUBMISSION");assert.equal(forged.stage,"WALLET_SUBMISSION");assert.equal(forged.providerCode,4001);const secrets=["a".repeat(64),`0x${"b".repeat(64)}`,"mnemonic: abandon ability able about above absent absorb abstract absurd abuse access accident","Authorization: Bearer supersecret","signature: "+"c".repeat(200),"A".repeat(120)];for(const secret of secrets)assert.doesNotMatch(redactSecrets(secret),/abandon|supersecret|bbbbbbbb|cccccccc|AAAAAAAAAA|aaaaaaaa/);const normalized=safeError({message:"safe",stack:"secret stack",nested:{privateKey:"secret"}},"POLLING");assert.doesNotMatch(normalized.message,/stack|privateKey|secret stack/)});
test("hostile JavaScript values can never escape safe normalization",()=>{const throwingGetter={};Object.defineProperty(throwingGetter,"message",{enumerable:true,get(){throw new Error("getter secret")}});const throwingCode={message:"safe"};Object.defineProperty(throwingCode,"code",{get(){throw new Error("code secret")}});const ownKeysProxy=new Proxy({},{ownKeys(){throw new Error("ownKeys secret")}});const getProxy=new Proxy({},{get(){throw new Error("get secret")},getOwnPropertyDescriptor(){throw new Error("descriptor secret")},getPrototypeOf(){throw new Error("prototype secret")}});const hostileError=new Error("initial");Object.defineProperty(hostileError,"message",{get(){throw new Error("message secret")}});const circular={};circular.self=circular;const symbol=Symbol("secret");const symbolObject={message:"safe",[symbol]:"private key"};const custom={toString(){throw new Error("toString secret")},toJSON(){throw new Error("toJSON secret")}};for(const value of [throwingGetter,throwingCode,ownKeysProxy,getProxy,hostileError,circular,symbolObject,custom]){assert.doesNotThrow(()=>safeMessage(value));assert.doesNotThrow(()=>safeError(value,"POLLING"));const normalized=normalizeFailure(value,"WALLET_SUBMISSION");assert.ok(normalized instanceof AppFailure);assert.equal(normalized.safe.stage,"WALLET_SUBMISSION")}assert.equal(safeError({message:"rejected",code:4001},"WALLET_SUBMISSION").providerCode,4001);assert.equal(safeError({message:"unknown chain",code:4902},"NETWORK_VERIFICATION").providerCode,4902);assert.doesNotMatch(safeMessage({message:"safe",nested:{privateKey:"0x"+"a".repeat(64)}}),/aaaa|private/i);assert.match(safeMessage("x".repeat(10000)),/^\[REDACTED_/)});
test("supplementary reads cannot change protocol finality",()=>{const final=activity({currentPhase:"finalized success",terminal:true,statusName:"FINALIZED",executionResult:"FINISHED_WITH_RETURN"});const next=applySupplementaryRead(final,{status:"OPEN"});assert.equal(next.terminal,true);assert.equal(next.currentPhase,"finalized success")});
test("post-check matching handles contract normalization, ambiguity, and address casing",()=>{const submitted={title:market.title,description:market.description,yes_rules:market.yes_rules,no_rules:market.no_rules,invalid_rules:market.invalid_rules,deadline:market.deadline};assert.equal(findUniqueCreatedMarket([market],submitted).market_id,"1");assert.equal(findUniqueCreatedMarket([market,{...market,market_id:"2"}],submitted),null);assert.equal(leaderboardPayout({[address.toUpperCase().replace("0X","0x")]:"9"},address),"9")});
test("all seven writes use shared submission path",async()=>{const detail=await readFile("app/markets/[id]/page.tsx","utf8");const create=await readFile("app/markets/create/page.tsx","utf8");for(const method of ["stake","submit_evidence","resolve_market","challenge_resolution","finalize_market","claim_winnings"])assert.match(detail,new RegExp(`send\\(\\\"${method}\\\"`));assert.match(create,/submitTransaction\(/);assert.match(detail,/submitTransaction\(/)});
test("wallet chooser exposes pending accessibility and stable focus lifetime",async()=>{const source=await readFile("app/components/wallet-provider.tsx","utf8"),chrome=await readFile("app/components/chrome.tsx","utf8");assert.match(source,/tabIndex=\{-1\} role=\"dialog\"/);assert.match(source,/aria-busy=\{connectionPending\}/);assert.match(source,/role=\"alert\"/);assert.match(source,/role=\"status\"/);assert.match(source,/disabled=\{connectionPending\}/);assert.match(source,/items\.length===0.*dialog\?\.focus\(\)/s);assert.doesNotMatch(source,/\[choosing,connectionPending,closeChooser\]/);assert.match(source,/setSelected\(detail\).*setAccount\(nextSnapshot\.account\)/s);assert.match(source,/gate\.current\.invalidate\(\).*setSelected\(undefined\)/s);assert.match(chrome,/disabled=\{connectionPending\|\|discoveryState===\"DISCOVERING\"\}/);assert.match(chrome,/aria-live=\"polite\"/)});
test("forbidden paths, wait-only monitor, and misleading status conversion are absent",async()=>{const files=["lib/genlayer.ts","lib/wallet.ts","lib/transactions.ts","lib/activity.ts","app/components/wallet-provider.tsx","app/page.tsx","app/docs/page.tsx","README.md","docs/V3_LIMITATIONS.md"];const source=(await Promise.all(files.map(f=>readFile(f,"utf8")))).join("\n");for(const forbidden of ["window.ethereum"+".providers","Wallet"+"Connect","wallet_"+"getSnaps","wallet_"+"requestSnaps","wallet_"+"invokeSnap","wallet_"+"snap","client."+"connect(","waitFor"+"Finalized","String(receipt."+"status","as "+"never"])assert.equal(source.includes(forbidden),false,forbidden);assert.match(source,/does not fetch or authenticate webpage contents/i)});
test("complete active documentation keeps the V3 accepted-state boundary truthful",async()=>{const files=["README.md","docs/README.md","docs/ARCHITECTURE.md","docs/DEPLOYMENT.md","docs/TRANSACTION_FINALITY.md","docs/V3_LIMITATIONS.md","docs/WALLET_AND_NETWORK.md","app/page.tsx","app/docs/page.tsx","app/markets/create/page.tsx","app/markets/[id]/page.tsx"],documents=new Map(await Promise.all(files.map(async file=>[file,await readFile(file,"utf8")]))),deployment=documents.get("docs/DEPLOYMENT.md"),all=[...documents.values()].join("\n");assert.match(deployment,/Historical V3 accepted-state smoke record — observed 2026-07-11/);assert.match(deployment,/`ACCEPTED` is nonterminal/i);assert.match(deployment,/is not protocol finality proof/i);assert.match(deployment,/success must be established separately from a receipt showing both `FINALIZED` and `FINISHED_WITH_RETURN`/i);assert.match(deployment,/market remained `OPEN` and unresolved/i);assert.match(deployment,/0\.001 GEN stake was visible as escrowed/i);assert.match(deployment,/may require Vercel authentication and is not cited as publicly verifiable/i);assert.doesNotMatch(deployment,/Current v3 Smoke-Test Proof/i);assert.doesNotMatch(deployment,/ACCEPTED or FINALIZED/i);assert.doesNotMatch(all,/(?:full|complete)(?: V3)? lifecycle (?:is|was|has been) verified/i);assert.match(all,/complete lifecycle (?:remains|remained|is) (?:not end-to-end verified|unverified)/i)});
test("contract working-tree diff is empty",async()=>{const {stdout}=await exec("git",["diff","--","contracts/truth_market.py"]);assert.equal(stdout,"")});
