import type { GenLayerTransaction } from "genlayer-js/types";
import { BRADBURY_CHAIN_ID, TRUTHMARKET_CONTRACT_ADDRESS } from "./config.ts";
import { getTransactionState, WRITE_METHODS } from "./genlayer.ts";
import { ADDRESS_RE, MARKET_ID_RE } from "./schemas.ts";

export const ACTIVITY_PHASES=["submitted","confirmation/accepted","ready to finalize","finalized success","execution failure","canceled","timeout","no majority","disagreement/failure","undetermined","retryable unknown polling error"] as const;
export const POLLING_STATES=["IDLE","ACTIVE","PAUSED","TERMINAL"] as const;
export const ACTION_LABELS={create_market:"Create market",stake:"Stake",submit_evidence:"Submit evidence",resolve_market:"Resolve market",challenge_resolution:"Challenge resolution",finalize_market:"Finalize market",claim_winnings:"Claim winnings"} as const;
export type ActivityPhase=typeof ACTIVITY_PHASES[number];
export type PollingState=typeof POLLING_STATES[number];
export type WriteMethod=typeof WRITE_METHODS[number];
export type ActivityStatusName="UNINITIALIZED"|"PENDING"|"PROPOSING"|"COMMITTING"|"REVEALING"|"ACCEPTED"|"UNDETERMINED"|"FINALIZED"|"CANCELED"|"APPEAL_REVEALING"|"APPEAL_COMMITTING"|"READY_TO_FINALIZE"|"VALIDATORS_TIMEOUT"|"LEADER_TIMEOUT";
export type ActivityResultName="IDLE"|"AGREE"|"DISAGREE"|"TIMEOUT"|"DETERMINISTIC_VIOLATION"|"NO_MAJORITY"|"MAJORITY_AGREE"|"MAJORITY_DISAGREE";
export type ActivityExecutionResult="NOT_VOTED"|"FINISHED_WITH_RETURN"|"FINISHED_WITH_ERROR";
export type SafeErrorStage="PREPARATION"|"CLIENT_INITIALIZATION"|"NETWORK_VERIFICATION"|"WALLET_SUBMISSION"|"HASH_VALIDATION"|"POLLING"|"STORAGE";
export type SafeError={stage:SafeErrorStage;message:string;providerCode?:string|number};
export type Activity={action:typeof ACTION_LABELS[WriteMethod];contractMethod:WriteMethod;marketId?:string;submittedAt:string;updatedAt:string;revision:number;transactionHash:`0x${string}`;currentPhase:ActivityPhase;terminal:boolean;pollingState:PollingState;pollingStoppedAt:string|null;statusName:ActivityStatusName|null;resultName:ActivityResultName|null;executionResult:ActivityExecutionResult|null;safeError:SafeError|null;supplementaryStateRead:unknown;chainId:number;contractAddress:string;walletAddress:string};
export type ActivityStorage=Pick<Storage,"getItem"|"setItem"|"key"|"length">;
export type ActivityLockManager={request<T>(name:string,optionsOrCallback:{ifAvailable?:boolean}|(()=>Promise<T>|T),callback?:(lock:unknown|null)=>Promise<T>|T):Promise<T>};
export type PersistenceOptions={locks?:ActivityLockManager|null};
export type PersistenceResult={activity:Activity;warning:SafeError|null;written:boolean};
export const HASH_RE=/^0x[a-fA-F0-9]{64}$/;

const STATUS_NAMES=new Set<ActivityStatusName>(["UNINITIALIZED","PENDING","PROPOSING","COMMITTING","REVEALING","ACCEPTED","UNDETERMINED","FINALIZED","CANCELED","APPEAL_REVEALING","APPEAL_COMMITTING","READY_TO_FINALIZE","VALIDATORS_TIMEOUT","LEADER_TIMEOUT"]);
const RESULT_NAMES=new Set<ActivityResultName>(["IDLE","AGREE","DISAGREE","TIMEOUT","DETERMINISTIC_VIOLATION","NO_MAJORITY","MAJORITY_AGREE","MAJORITY_DISAGREE"]);
const EXECUTION_RESULTS=new Set<ActivityExecutionResult>(["NOT_VOTED","FINISHED_WITH_RETURN","FINISHED_WITH_ERROR"]);
const SAFE_STAGES=new Set<SafeErrorStage>(["PREPARATION","CLIENT_INITIALIZATION","NETWORK_VERIFICATION","WALLET_SUBMISSION","HASH_VALIDATION","POLLING","STORAGE"]);
const PHASE_RANK:Record<ActivityPhase,number>={"retryable unknown polling error":0,"submitted":1,"undetermined":1,"confirmation/accepted":2,"ready to finalize":3,"canceled":4,"timeout":4,"no majority":4,"disagreement/failure":4,"execution failure":5,"finalized success":6};
const EVENT_PREFIX="truthmarket:activity-event";
const INTERNAL_EVENT="truthmarket:activity-updated";
const EVENT_ID_RE=/^(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|[0-9a-f]{32,})$/i;
const activeMonitors=new Set<string>();
const STORAGE_WARNING:SafeError={stage:"STORAGE",message:"Transaction submitted, but browser-local Activity could not be saved. Do not resubmit; use the transaction hash and explorer link."};
const POLLING_PAUSED_MESSAGE="Automatic polling paused because the bounded polling window ended. Use Retry polling only; do not resubmit the transaction.";

function isObject(value:unknown):value is Record<string,unknown>{return value!==null&&typeof value==="object"&&!Array.isArray(value)}
function isIso(value:unknown):value is string{return typeof value==="string"&&!Number.isNaN(Date.parse(value))&&new Date(value).toISOString()===value}
function nullableEnum<T extends string>(value:unknown,values:Set<T>):value is T|null{return value===null||(typeof value==="string"&&values.has(value as T))}
function guardSafeError(value:unknown):value is SafeError|null{if(value===null)return true;if(!isObject(value))return false;try{const keys=Object.keys(value);return keys.includes("stage")&&keys.includes("message")&&!keys.some(k=>!["stage","message","providerCode"].includes(k))&&typeof value.message==="string"&&value.message.length<=500&&typeof value.stage==="string"&&SAFE_STAGES.has(value.stage as SafeErrorStage)&&(value.providerCode===undefined||typeof value.providerCode==="string"||typeof value.providerCode==="number")}catch{return false}}
type ProtocolInput={statusName:unknown;resultName:unknown;executionResult:unknown;pollingError?:boolean};
type DerivedProtocolState={phase:ActivityPhase;terminal:boolean;statusName:ActivityStatusName|null;resultName:ActivityResultName|null;executionResult:ActivityExecutionResult|null;known:boolean};
const TERMINAL_RESULTS=new Set<ActivityResultName>(["TIMEOUT","NO_MAJORITY","DISAGREE","MAJORITY_DISAGREE","DETERMINISTIC_VIOLATION"]);
const IN_FLIGHT_STATUSES=new Set<ActivityStatusName>(["UNINITIALIZED","PENDING","PROPOSING","COMMITTING","REVEALING","APPEAL_REVEALING","APPEAL_COMMITTING"]);
export function deriveProtocolState(input:ProtocolInput):DerivedProtocolState|null{
 const rawStatus=input.statusName,rawResult=input.resultName,rawExecution=input.executionResult;
 const status=rawStatus===null||rawStatus===undefined?null:typeof rawStatus==="string"&&STATUS_NAMES.has(rawStatus as ActivityStatusName)?rawStatus as ActivityStatusName:undefined;
 const result=rawResult===null||rawResult===undefined?null:typeof rawResult==="string"&&RESULT_NAMES.has(rawResult as ActivityResultName)?rawResult as ActivityResultName:undefined;
 const execution=rawExecution===null||rawExecution===undefined?null:typeof rawExecution==="string"&&EXECUTION_RESULTS.has(rawExecution as ActivityExecutionResult)?rawExecution as ActivityExecutionResult:undefined;
 if(status===undefined||result===undefined||execution===undefined)return{phase:"retryable unknown polling error",terminal:false,statusName:null,resultName:null,executionResult:null,known:false};
 const successfulExecution=execution==="FINISHED_WITH_RETURN";
 if(status==="FINALIZED")return{phase:successfulExecution?"finalized success":"execution failure",terminal:true,statusName:status,resultName:result,executionResult:execution,known:true};
 if(status==="CANCELED")return{phase:"canceled",terminal:true,statusName:status,resultName:result,executionResult:execution,known:true};
 if(status==="VALIDATORS_TIMEOUT"||status==="LEADER_TIMEOUT")return{phase:"timeout",terminal:true,statusName:status,resultName:result,executionResult:execution,known:true};
 if(status==="ACCEPTED"){
  if(result!==null&&TERMINAL_RESULTS.has(result))return null;
  return{phase:"confirmation/accepted",terminal:false,statusName:status,resultName:result,executionResult:execution,known:true};
 }
 if(status==="READY_TO_FINALIZE"){
  if(result!==null&&TERMINAL_RESULTS.has(result))return null;
  return{phase:"ready to finalize",terminal:false,statusName:status,resultName:result,executionResult:execution,known:true};
 }
 if(status==="UNDETERMINED"){
  if(result==="TIMEOUT")return{phase:"timeout",terminal:true,statusName:status,resultName:result,executionResult:execution,known:true};
  if(result==="NO_MAJORITY")return{phase:"no majority",terminal:true,statusName:status,resultName:result,executionResult:execution,known:true};
  if(result==="DISAGREE"||result==="MAJORITY_DISAGREE"||result==="DETERMINISTIC_VIOLATION")return{phase:"disagreement/failure",terminal:true,statusName:status,resultName:result,executionResult:execution,known:true};
  return{phase:input.pollingError?"retryable unknown polling error":"undetermined",terminal:false,statusName:status,resultName:result,executionResult:execution,known:true};
 }
 if(status!==null&&IN_FLIGHT_STATUSES.has(status)){
  if(successfulExecution||result!==null&&TERMINAL_RESULTS.has(result))return null;
  return{phase:input.pollingError?"retryable unknown polling error":"submitted",terminal:false,statusName:status,resultName:result,executionResult:execution,known:true};
 }
 if(status===null&&result===null&&execution===null)return{phase:input.pollingError?"retryable unknown polling error":"submitted",terminal:false,statusName:null,resultName:null,executionResult:null,known:true};
 return null;
}
function finalityInvariant(value:Record<string,unknown>){const polling=value.pollingState,stopped=value.pollingStoppedAt;if(value.terminal!==(polling==="TERMINAL"))return false;if((polling==="PAUSED")!==(stopped!==null))return false;const pollingError=value.currentPhase==="retryable unknown polling error"&&isObject(value.safeError)&&value.safeError.stage==="POLLING";const derived=deriveProtocolState({statusName:value.statusName,resultName:value.resultName,executionResult:value.executionResult,pollingError});return derived!==null&&derived.phase===value.currentPhase&&derived.terminal===value.terminal}
export function guardActivity(value:unknown,expected?:{wallet?:string;hash?:string;contract?:string;chain?:number}):Activity|null{if(!isObject(value))return null;const required=["action","contractMethod","submittedAt","updatedAt","revision","transactionHash","currentPhase","terminal","pollingState","pollingStoppedAt","statusName","resultName","executionResult","safeError","supplementaryStateRead","chainId","contractAddress","walletAddress"];const allowed=[...required,"marketId"];try{const keys=Object.keys(value);if(required.some(k=>!keys.includes(k))||keys.some(k=>!allowed.includes(k))||!WRITE_METHODS.includes(value.contractMethod as WriteMethod)||value.action!==ACTION_LABELS[value.contractMethod as WriteMethod]||!isIso(value.submittedAt)||!isIso(value.updatedAt)||!Number.isInteger(value.revision)||Number(value.revision)<0||typeof value.transactionHash!=="string"||!HASH_RE.test(value.transactionHash)||!ACTIVITY_PHASES.includes(value.currentPhase as ActivityPhase)||typeof value.terminal!=="boolean"||!POLLING_STATES.includes(value.pollingState as PollingState)||(value.pollingStoppedAt!==null&&!isIso(value.pollingStoppedAt))||!nullableEnum(value.statusName,STATUS_NAMES)||!nullableEnum(value.resultName,RESULT_NAMES)||!nullableEnum(value.executionResult,EXECUTION_RESULTS)||!guardSafeError(value.safeError)||value.chainId!==BRADBURY_CHAIN_ID||typeof value.contractAddress!=="string"||!ADDRESS_RE.test(value.contractAddress)||value.contractAddress.toLowerCase()!==TRUTHMARKET_CONTRACT_ADDRESS.toLowerCase()||typeof value.walletAddress!=="string"||!ADDRESS_RE.test(value.walletAddress)||!finalityInvariant(value))return null;if(value.marketId!==undefined&&(typeof value.marketId!=="string"||!MARKET_ID_RE.test(value.marketId)))return null;if(expected?.wallet&&value.walletAddress.toLowerCase()!==expected.wallet.toLowerCase())return null;if(expected?.hash&&value.transactionHash.toLowerCase()!==expected.hash.toLowerCase())return null;if(expected?.contract&&value.contractAddress.toLowerCase()!==expected.contract.toLowerCase())return null;if(expected?.chain!==undefined&&value.chainId!==expected.chain)return null;return value as Activity}catch{return null}}

export function actionForMethod(method:WriteMethod){return ACTION_LABELS[method]}
function newEventId(){try{const uuid=globalThis.crypto.randomUUID();if(EVENT_ID_RE.test(uuid))return uuid}catch{/* fall through */}const bytes=new Uint8Array(24);try{globalThis.crypto.getRandomValues(bytes)}catch{for(let i=0;i<bytes.length;i++)bytes[i]=Math.floor(Math.random()*256)}return `${Date.now().toString(16)}${Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("")}`}
export function activityKey(wallet:string,hash:string,eventId=newEventId()){return `${EVENT_PREFIX}:${BRADBURY_CHAIN_ID}:${TRUTHMARKET_CONTRACT_ADDRESS.toLowerCase()}:${wallet.toLowerCase()}:${hash.toLowerCase()}:${eventId}`}
export function activityLockName(wallet:string,hash:string){return `truthmarket-activity-${BRADBURY_CHAIN_ID}-${TRUTHMARKET_CONTRACT_ADDRESS.toLowerCase()}-${wallet.toLowerCase()}-${hash.toLowerCase()}`}
export function monitorLockName(wallet:string,hash:string){return `${activityLockName(wallet,hash)}-monitor`}
function parseJournalKey(key:string|null){if(!key)return null;const parts=key.split(":");if(parts.length!==7||parts[0]!=="truthmarket"||parts[1]!=="activity-event")return null;const chain=Number(parts[2]);const [, , ,contract,wallet,hash,eventId]=parts;if(chain!==BRADBURY_CHAIN_ID||!ADDRESS_RE.test(contract)||contract.toLowerCase()!==TRUTHMARKET_CONTRACT_ADDRESS.toLowerCase()||!ADDRESS_RE.test(wallet)||!HASH_RE.test(hash)||!EVENT_ID_RE.test(eventId))return null;return{chain,contract,wallet,hash,eventId}}
export function parseStoredActivity(raw:string|null,expected?:{wallet?:string;hash?:string;contract?:string;chain?:number}){if(!raw)return null;try{return guardActivity(JSON.parse(raw),expected)}catch{return null}}
function protocolFingerprint(value:Activity){return JSON.stringify([value.currentPhase,value.statusName,value.resultName,value.executionResult,value.terminal])}
function fingerprint(value:Activity){return JSON.stringify([value.pollingState,value.pollingStoppedAt,value.safeError,value.supplementaryStateRead,value.contractMethod,value.marketId??"",value.submittedAt,value.walletAddress.toLowerCase(),value.transactionHash.toLowerCase()])}
export function compareActivityStrength(a:Activity,b:Activity){const phase=PHASE_RANK[a.currentPhase]-PHASE_RANK[b.currentPhase];if(phase!==0)return phase;const protocol=protocolFingerprint(a).localeCompare(protocolFingerprint(b));if(protocol!==0)return protocol;if(a.revision!==b.revision)return a.revision-b.revision;return fingerprint(a).localeCompare(fingerprint(b))}
export function deterministicActivityWinner(a:Activity,b:Activity){const validA=guardActivity(a),validB=guardActivity(b);if(!validA&&!validB)throw new Error("No valid Activity candidate");if(!validA)return validB!;if(!validB)return validA;return compareActivityStrength(validA,validB)>=0?validA:validB}
export function loadActivities(storage:ActivityStorage,wallet:string){const winners=new Map<string,Activity>();try{for(let i=0;i<storage.length;i++){const key=storage.key(i),parsed=parseJournalKey(key);if(!key||!parsed||parsed.wallet.toLowerCase()!==wallet.toLowerCase())continue;const item=parseStoredActivity(storage.getItem(key),{wallet:parsed.wallet,hash:parsed.hash,contract:parsed.contract,chain:parsed.chain});if(!item)continue;const previous=winners.get(parsed.hash.toLowerCase());winners.set(parsed.hash.toLowerCase(),previous?deterministicActivityWinner(previous,item):item)}}catch{return[]}return [...winners.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}
function storageResult(activity:Activity,written:boolean,warning:SafeError|null):PersistenceResult{return{activity,written,warning}}
function defaultLocks():ActivityLockManager|null{try{return typeof navigator!=="undefined"&&navigator.locks?navigator.locks as unknown as ActivityLockManager:null}catch{return null}}
function notify(activity:Activity){try{if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent(INTERNAL_EVENT,{detail:activity}))}catch{/* best effort */}}
function appendJournal(storage:ActivityStorage,candidate:Activity):PersistenceResult{const valid=guardActivity(candidate);if(!valid)return storageResult(candidate,false,{stage:"STORAGE",message:"Invalid browser-local Activity transition was not saved."});try{const existing=loadActivities(storage,valid.walletAddress).find(item=>item.transactionHash.toLowerCase()===valid.transactionHash.toLowerCase());const snapshot={...valid,revision:Math.max(existing?.revision??-1,valid.revision)+1,updatedAt:new Date().toISOString()};const checked=guardActivity(snapshot);if(!checked)return storageResult(candidate,false,{stage:"STORAGE",message:"Invalid browser-local Activity transition was not saved."});let key=activityKey(checked.walletAddress,checked.transactionHash);for(let attempt=0;storage.getItem(key)!==null&&attempt<4;attempt++)key=activityKey(checked.walletAddress,checked.transactionHash);if(storage.getItem(key)!==null)return storageResult(candidate,false,STORAGE_WARNING);storage.setItem(key,JSON.stringify(checked));const inserted=parseStoredActivity(storage.getItem(key),{wallet:checked.walletAddress,hash:checked.transactionHash,contract:checked.contractAddress,chain:checked.chainId});if(!inserted)return storageResult(checked,false,STORAGE_WARNING);const derived=loadActivities(storage,checked.walletAddress).find(item=>item.transactionHash.toLowerCase()===checked.transactionHash.toLowerCase());if(!derived)return storageResult(checked,false,STORAGE_WARNING);notify(derived);return storageResult(derived,true,null)}catch{return storageResult(candidate,false,STORAGE_WARNING)}}
export async function persistActivity(storage:ActivityStorage,candidate:Activity,options:PersistenceOptions={}):Promise<PersistenceResult>{if(!guardActivity(candidate))return storageResult(candidate,false,{stage:"STORAGE",message:"Invalid browser-local Activity transition was not saved."});const locks=options.locks===undefined?defaultLocks():options.locks;if(locks){try{return await locks.request(activityLockName(candidate.walletAddress,candidate.transactionHash),()=>appendJournal(storage,candidate))}catch{return storageResult(candidate,false,STORAGE_WARNING)}}return appendJournal(storage,candidate)}

export function classifyReceipt(receipt:Pick<GenLayerTransaction,"statusName"|"resultName"|"txExecutionResultName">):Pick<Activity,"currentPhase"|"terminal"|"statusName"|"resultName"|"executionResult">{const derived=deriveProtocolState({statusName:receipt.statusName,resultName:receipt.resultName,executionResult:receipt.txExecutionResultName});if(!derived)return{currentPhase:"retryable unknown polling error",terminal:false,statusName:null,resultName:null,executionResult:null};return{currentPhase:derived.phase,terminal:derived.terminal,statusName:derived.statusName,resultName:derived.resultName,executionResult:derived.executionResult}}

export type MonitorOptions={storage:ActivityStorage;getTransaction?:(hash:string)=>Promise<GenLayerTransaction>;supplementary?:()=>Promise<unknown>;intervalMs?:number;maxPolls?:number;sleep?:(ms:number)=>Promise<void>;persistence?:PersistenceOptions;monitorLocks?:ActivityLockManager|null};
const delay=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
async function runMonitor(initial:Activity,options:MonitorOptions){const id=activityLockName(initial.walletAddress,initial.transactionHash);if(activeMonitors.has(id))return loadActivities(options.storage,initial.walletAddress).find(a=>a.transactionHash.toLowerCase()===initial.transactionHash.toLowerCase())??initial;activeMonitors.add(id);let current=initial;try{const started=await persistActivity(options.storage,{...initial,revision:initial.revision+1,pollingState:"ACTIVE",pollingStoppedAt:null},options.persistence);current=started.activity;const getTransaction=options.getTransaction??getTransactionState,maxPolls=Math.max(1,options.maxPolls??120);for(let poll=0;poll<maxPolls&&!current.terminal;poll++){try{const classified=classifyReceipt(await getTransaction(current.transactionHash));const unknown=classified.currentPhase==="retryable unknown polling error";const protocol=unknown?{currentPhase:current.currentPhase,terminal:current.terminal,statusName:current.statusName,resultName:current.resultName,executionResult:current.executionResult}:classified;const pollingError=unknown?{stage:"POLLING" as const,message:"The SDK returned an unknown transaction state. Polling will continue without changing the last valid protocol phase."}:null;current=(await persistActivity(options.storage,{...current,revision:current.revision+1,...protocol,pollingState:protocol.terminal?"TERMINAL":"ACTIVE",pollingStoppedAt:null,safeError:pollingError},options.persistence)).activity;if(current.terminal&&current.currentPhase==="finalized success"&&options.supplementary){try{current=(await persistActivity(options.storage,{...current,revision:current.revision+1,supplementaryStateRead:await options.supplementary()},options.persistence)).activity}catch(error){current=(await persistActivity(options.storage,{...current,revision:current.revision+1,supplementaryStateRead:{available:false,error:safeMessage(error)}},options.persistence)).activity}}}catch(error){const phase=current.currentPhase==="submitted"||current.currentPhase==="undetermined"?"retryable unknown polling error":current.currentPhase;current=(await persistActivity(options.storage,{...current,revision:current.revision+1,currentPhase:phase,pollingState:"ACTIVE",pollingStoppedAt:null,safeError:safeError(error,"POLLING")},options.persistence)).activity}if(!current.terminal&&poll+1<maxPolls)await(options.sleep??delay)(options.intervalMs??5000)}if(!current.terminal){current=(await persistActivity(options.storage,{...current,revision:current.revision+1,pollingState:"PAUSED",pollingStoppedAt:new Date().toISOString(),safeError:{stage:"POLLING",message:POLLING_PAUSED_MESSAGE}},options.persistence)).activity}return current}finally{activeMonitors.delete(id)}}
export async function monitorActivity(initial:Activity,options:MonitorOptions):Promise<Activity>{const valid=guardActivity(initial);if(!valid)return initial;if(valid.terminal)return valid;const locks=options.monitorLocks===undefined?defaultLocks():options.monitorLocks;if(locks){try{return await locks.request(monitorLockName(valid.walletAddress,valid.transactionHash),{ifAvailable:true},lock=>lock?runMonitor(valid,options):loadActivities(options.storage,valid.walletAddress).find(a=>a.transactionHash.toLowerCase()===valid.transactionHash.toLowerCase())??valid)}catch{return valid}}return runMonitor(valid,options)}
export function resumeActivities(storage:ActivityStorage,wallet:string,options:Omit<MonitorOptions,"storage">={}){const pending=loadActivities(storage,wallet).filter(item=>!item.terminal);for(const item of pending)void monitorActivity(item,{...options,storage}).catch(()=>{});return pending.length}
export function subscribeActivities(wallet:string,callback:(items:Activity[])=>void){if(typeof window==="undefined")return()=>{};const update=()=>callback(loadActivities(window.localStorage,wallet));const storageHandler=(event:StorageEvent)=>{const parsed=parseJournalKey(event.key);if(parsed?.wallet.toLowerCase()===wallet.toLowerCase())update()};window.addEventListener("storage",storageHandler);window.addEventListener(INTERNAL_EVENT,update);return()=>{window.removeEventListener("storage",storageHandler);window.removeEventListener(INTERNAL_EVENT,update)}}
export function reconcileStorageEvent(_storage:ActivityStorage,wallet:string,event:{key:string|null;newValue:string|null}){const parsed=parseJournalKey(event.key);if(!parsed||parsed.wallet.toLowerCase()!==wallet.toLowerCase()||event.newValue===null)return null;return parseStoredActivity(event.newValue,{wallet:parsed.wallet,hash:parsed.hash,contract:parsed.contract,chain:parsed.chain})}
export function activeMonitorCount(){return activeMonitors.size}
export function resetActivityMonitorsForTests(){activeMonitors.clear()}
export function applySupplementaryRead(activity:Activity,result:unknown):Activity{return{...activity,supplementaryStateRead:result}}

function ownValue(value:unknown,key:string):unknown{try{if(value===null||(typeof value!=="object"&&typeof value!=="function"))return undefined;const descriptor=Object.getOwnPropertyDescriptor(value,key);return descriptor&&"value" in descriptor?descriptor.value:undefined}catch{return undefined}}
function ownPrimitive(value:unknown,key:string):string|number|boolean|undefined{const primitive=ownValue(value,key);return typeof primitive==="string"||typeof primitive==="number"||typeof primitive==="boolean"?primitive:undefined}
const MAX_ERROR_CAUSE_DEPTH=6;
export function extractProviderCode(error:unknown):string|number|undefined{try{const seen=new Set<object>();let current=error;for(let depth=0;depth<=MAX_ERROR_CAUSE_DEPTH;depth++){if(current===null||(typeof current!=="object"&&typeof current!=="function"))return undefined;const container=current as object;if(seen.has(container))return undefined;seen.add(container);const code=ownValue(current,"code");if(typeof code==="string"||typeof code==="number")return code;current=ownValue(current,"cause")}return undefined}catch{return undefined}}
function serializeUnknown(error:unknown){try{if(typeof error==="string")return error;if(typeof error==="number"||typeof error==="boolean"||typeof error==="bigint")return String(error);const message=ownPrimitive(error,"message");if(typeof message==="string")return message;const reason=ownPrimitive(error,"reason");if(typeof reason==="string")return reason;return"Unknown wallet, RPC, or SDK error"}catch{return"Unknown wallet, RPC, or SDK error"}}
export function redactSecrets(value:string){try{let output=value.replace(/\b(?:0x)?[a-fA-F0-9]{64}\b/g,"[REDACTED_KEY_OR_SIGNATURE]").replace(/\b(?:0x)?[a-fA-F0-9]{96,}\b/g,"[REDACTED_HEX]").replace(/\b[A-Za-z0-9+/]{80,}={0,2}\b/g,"[REDACTED_BASE64]").replace(/(?:authorization\s*:\s*(?:bearer\s+)?|bearer\s+|access[_ -]?token\s*[:=]?\s*|cookie\s*[:=]\s*|set-cookie\s*[:=]\s*)[^\s,;]+/gi,"[REDACTED_CREDENTIAL]").replace(/(?:private[_ -]?key|seed phrase|mnemonic|signature|serialized signed transaction|signed transaction)\s*[:=]?\s*[^,;\n]+/gi,"[REDACTED_SECRET]");const words=output.trim().split(/\s+/);if(words.length>=12&&words.length<=24&&words.every(word=>/^[a-z]+$/i.test(word)))output="[REDACTED_MNEMONIC]";return output.length>400?"[REDACTED_LARGE_PAYLOAD]":output}catch{return"Unknown wallet, RPC, or SDK error"}}
export function safeMessage(error:unknown){try{const message=redactSecrets(serializeUnknown(error));return message&&message!=="{}"?message:"Unknown wallet, RPC, or SDK error"}catch{return"Unknown wallet, RPC, or SDK error"}}
export function safeError(error:unknown,stage:SafeErrorStage):SafeError{try{const code=extractProviderCode(error);return code===undefined?{stage,message:safeMessage(error)}:{stage,message:safeMessage(error),providerCode:code}}catch{return{stage,message:"Unknown wallet, RPC, or SDK error"}}}
