import { readTruthMarket,type ContractViewMethod } from "./genlayer.ts";
import { parseAndGuard,type Market,type Position,type Resolution,type Challenge,type Leaderboard } from "./schemas.ts";
import type { WriteMethod } from "./transactions.ts";
type Context={method:WriteMethod;marketId?:string;account:string;submitted?:Record<string,string>;before?:Record<string,string>};
async function read(method:ContractViewMethod,args:string[]=[]):Promise<unknown>{return parseAndGuard(method,await readTruthMarket(method,args))}
function contractClean(value:string,limit:number){let cleaned=value.replace(/\r/g," ").replaceAll('"',"'");while(cleaned.includes("  "))cleaned=cleaned.replaceAll("  "," ");return cleaned.slice(0,limit)}
export function findUniqueCreatedMarket(markets:Market[],raw:Record<string,string>){const fields={title:contractClean((raw.title??"").trim(),140),description:contractClean((raw.description??"").trim(),1200),yes_rules:contractClean((raw.yes_rules??"").trim(),1000),no_rules:contractClean((raw.no_rules??"").trim(),1000),invalid_rules:contractClean((raw.invalid_rules??"").trim(),1000),deadline:raw.deadline??""};const matches=markets.filter(m=>(Object.keys(fields) as (keyof typeof fields)[]).every(k=>m[k]===fields[k]));return matches.length===1?matches[0]:null}
export function leaderboardPayout(leaderboard:Leaderboard,account:string){return Object.entries(leaderboard).find(([key])=>key.toLowerCase()===account.toLowerCase())?.[1]}
export async function postFinalizationCheck(context:Context){const {method,marketId,account}=context;if(method==="create_market"){const match=findUniqueCreatedMarket(await read("list_markets") as Market[],context.submitted??{});return match?{available:true,verified:true,marketId:match.market_id}:{available:false,verified:false,reason:"An exact unique resulting market ID could not be derived safely"}}
 if(!marketId)return{available:false,verified:false,reason:"Market ID unavailable"};const market=await read("get_market",[marketId]) as Market;
 if(method==="stake"){const position=await read("get_user_position",[marketId,account]) as Position;const side=context.submitted?.side?.toUpperCase();const pool=side&&`${side.toLowerCase()}_pool` as keyof Market;const beforeAmount=BigInt(context.before?.positionAmount??"0"),beforePool=BigInt(context.before?.pool??"0");return{available:true,verified:position.found&&position.side===side&&BigInt(position.amount)>beforeAmount&&!!pool&&BigInt(market[pool] as string)>beforePool,position,pool:pool?market[pool]:undefined}}
 if(method==="submit_evidence")return{available:true,verified:BigInt(market.evidence_count)>BigInt(context.before?.evidenceCount??"0"),evidenceCount:market.evidence_count};
 if(method==="resolve_market"){const resolution=await read("get_resolution",[marketId]) as Resolution;return{available:true,verified:market.status==="ACCEPTED"&&market.resolution_id!==""&&resolution.found&&resolution.resolution_id===market.resolution_id,marketStatus:market.status,resolutionId:market.resolution_id,resolution}}
 if(method==="challenge_resolution"){const challenges=await read("list_challenges",[marketId]) as Challenge[];return{available:true,verified:market.status==="CHALLENGED"&&challenges.length>Number(context.before?.challengeCount??"0"),marketStatus:market.status,challengeCount:challenges.length}}
 if(method==="finalize_market")return{available:true,verified:market.status==="FINALIZED",marketStatus:market.status};
 const position=await read("get_user_position",[marketId,account]) as Position;const leaderboard=await read("get_leaderboard") as Leaderboard;const payout=leaderboardPayout(leaderboard,account);return{available:true,verified:position.claimed==="true"&&payout!==undefined,positionClaimed:position.claimed,leaderboardReadable:true,payout}}
