export const ADDRESS_RE = /^0x[a-fA-F0-9]{40}$/;
export const CANONICAL_UINT_RE = /^(0|[1-9][0-9]*)$/;
export const MARKET_ID_RE = /^[1-9][0-9]*$/;

export type Market = { market_id:string; creator:string; title:string; description:string; yes_rules:string; no_rules:string; invalid_rules:string; deadline:string; status:"OPEN"|"ACCEPTED"|"CHALLENGED"|"FINALIZED"; created_at:string; resolved_at:string; yes_pool:string; no_pool:string; invalid_pool:string; total_pool:string; evidence_count:string; resolution_id:string };
export type Position = { market_id:string; user:string; side:""|"YES"|"NO"|"INVALID"; amount:string; claimed:"true"|"false"; found:boolean };
export type Evidence = { evidence_id:string; market_id:string; submitter:string; url:string; note:string; submitted_at:string };
export type ResolutionFound = { found:true; resolution_id:string; market_id:string; verdict:"YES"|"NO"|"INVALID"|"UNRESOLVED"; confidence:"LOW"|"MEDIUM"|"HIGH"; reasoning:string; accepted_sources:string[]; rejected_sources:{url:string;reason:string}[]; risk_flags:string[]; resolver:string; created_at:string; challenge_count:string };
export type Resolution = {found:false}|ResolutionFound;
export type Challenge = { challenge_id:string; market_id:string; challenger:string; evidence_url:string; reason:string; created_at:string };
export type Stats = { market_count:string; finalized_count:string; total_volume:string };
export type Leaderboard = Record<string,string>;

function record(value:unknown): Record<string,unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Expected an object"); return value as Record<string,unknown>; }
function exact(value:unknown, keys:string[]) { const r=record(value); const actual=Object.keys(r).sort(); const expected=[...keys].sort(); if (actual.length!==expected.length || actual.some((k,i)=>k!==expected[i])) throw new Error("Response keys do not match the V3 schema"); return r; }
function str(r:Record<string,unknown>, key:string) { if(typeof r[key]!=="string") throw new Error(`${key} must be a string`); return r[key] as string; }
function uint(r:Record<string,unknown>, key:string) { const v=str(r,key); if(!CANONICAL_UINT_RE.test(v)) throw new Error(`${key} must be a canonical unsigned integer string`); return v; }
function id(r:Record<string,unknown>, key:string) { const v=str(r,key); if(!MARKET_ID_RE.test(v)) throw new Error(`${key} must be a canonical positive integer string`); return v; }
function address(r:Record<string,unknown>, key:string) { const v=str(r,key); if(!ADDRESS_RE.test(v)) throw new Error(`${key} must be an Ethereum address`); return v; }
function strings(v:unknown,key:string):string[]{ if(!Array.isArray(v)||v.some(x=>typeof x!=="string")) throw new Error(`${key} must be a string array`); return v; }

const marketKeys=["market_id","creator","title","description","yes_rules","no_rules","invalid_rules","deadline","status","created_at","resolved_at","yes_pool","no_pool","invalid_pool","total_pool","evidence_count","resolution_id"];
export function guardMarket(v:unknown):Market { const r=exact(v,marketKeys); const status=str(r,"status"); if(!["OPEN","ACCEPTED","CHALLENGED","FINALIZED"].includes(status)) throw new Error("Unknown market status"); ["yes_pool","no_pool","invalid_pool","total_pool","evidence_count"].forEach(k=>uint(r,k)); id(r,"market_id"); address(r,"creator"); ["title","description","yes_rules","no_rules","invalid_rules","deadline","created_at","resolved_at","resolution_id"].forEach(k=>str(r,k)); if(r.resolution_id!==""&&!MARKET_ID_RE.test(r.resolution_id as string)) throw new Error("Invalid resolution_id"); return r as Market; }
export function guardMarkets(v:unknown):Market[]{ if(!Array.isArray(v)) throw new Error("Markets must be an array"); return v.map(guardMarket); }
export function guardPosition(v:unknown):Position { const r=exact(v,["market_id","user","side","amount","claimed","found"]); id(r,"market_id"); address(r,"user"); uint(r,"amount"); if(!["","YES","NO","INVALID"].includes(str(r,"side"))) throw new Error("Unknown position side"); if(!["true","false"].includes(str(r,"claimed"))||typeof r.found!=="boolean") throw new Error("Invalid position state"); return r as Position; }
export function guardEvidence(v:unknown):Evidence { const r=exact(v,["evidence_id","market_id","submitter","url","note","submitted_at"]); id(r,"evidence_id"); id(r,"market_id"); address(r,"submitter"); ["url","note","submitted_at"].forEach(k=>str(r,k)); return r as Evidence; }
export function guardEvidenceList(v:unknown):Evidence[]{ if(!Array.isArray(v)) throw new Error("Evidence must be an array"); return v.map(guardEvidence); }
export function guardResolution(v:unknown):Resolution { const base=record(v); if(base.found===false){ exact(v,["found"]); return {found:false}; } const r=exact(v,["found","resolution_id","market_id","verdict","confidence","reasoning","accepted_sources","rejected_sources","risk_flags","resolver","created_at","challenge_count"]); if(r.found!==true) throw new Error("Invalid resolution found flag"); id(r,"resolution_id");id(r,"market_id"); address(r,"resolver"); uint(r,"challenge_count"); if(!["YES","NO","INVALID","UNRESOLVED"].includes(str(r,"verdict"))) throw new Error("Unknown verdict"); if(!["LOW","MEDIUM","HIGH"].includes(str(r,"confidence"))) throw new Error("Unknown confidence"); ["reasoning","created_at"].forEach(k=>str(r,k)); strings(r.accepted_sources,"accepted_sources"); strings(r.risk_flags,"risk_flags"); if(!Array.isArray(r.rejected_sources)) throw new Error("rejected_sources must be an array"); r.rejected_sources.forEach(x=>{const q=exact(x,["url","reason"]);str(q,"url");str(q,"reason")}); return r as ResolutionFound; }
export function guardChallenge(v:unknown):Challenge { const r=exact(v,["challenge_id","market_id","challenger","evidence_url","reason","created_at"]);id(r,"challenge_id");id(r,"market_id");address(r,"challenger");["evidence_url","reason","created_at"].forEach(k=>str(r,k));return r as Challenge; }
export function guardChallenges(v:unknown):Challenge[]{if(!Array.isArray(v))throw new Error("Challenges must be an array");return v.map(guardChallenge)}
export function guardStats(v:unknown):Stats {const r=exact(v,["market_count","finalized_count","total_volume"]);["market_count","finalized_count","total_volume"].forEach(k=>uint(r,k));return r as Stats}
export function guardLeaderboard(v:unknown):Leaderboard {const r=record(v);for(const [k,val] of Object.entries(r)){if(!ADDRESS_RE.test(k)||typeof val!=="string"||!CANONICAL_UINT_RE.test(val))throw new Error("Invalid leaderboard entry")}return r as Leaderboard}
export const RESPONSE_GUARDS={get_market:guardMarket,list_markets:guardMarkets,get_user_position:guardPosition,list_evidence:guardEvidenceList,get_resolution:guardResolution,list_challenges:guardChallenges,get_stats:guardStats,get_leaderboard:guardLeaderboard} as const;
export function parseAndGuard(method:keyof typeof RESPONSE_GUARDS,value:unknown){let parsed=value;if(typeof parsed==="string"){const t=parsed.trim();if(/^\s*</.test(t)||/<!doctype|<html/i.test(t))throw new Error("Upstream returned an HTML or gateway response");try{parsed=JSON.parse(t)}catch{throw new Error("Upstream returned invalid JSON")}}switch(method){case"get_market":return guardMarket(parsed);case"list_markets":return guardMarkets(parsed);case"get_user_position":return guardPosition(parsed);case"list_evidence":return guardEvidenceList(parsed);case"get_resolution":return guardResolution(parsed);case"list_challenges":return guardChallenges(parsed);case"get_stats":return guardStats(parsed);case"get_leaderboard":return guardLeaderboard(parsed)}}
