import { BRADBURY_CHAIN_ID_HEX, BRADBURY_RPC, BRADBURY_EXPLORER } from "./config.ts";

export interface Eip1193Provider { request(args:{method:string;params?:unknown[]}):Promise<unknown>; on?(event:string,handler:(...args:unknown[])=>void):void; removeListener?(event:string,handler:(...args:unknown[])=>void):void }
export type ProviderInfo={uuid:string;name:string;icon:string;rdns:string};
export type ProviderDetail={info:ProviderInfo;provider:Eip1193Provider};
export type DiscoveryState="DISCOVERING"|"COMPLETE";
export type ConnectionGate={begin:()=>number;invalidate:()=>void;isCurrent:(token:number)=>boolean};
export const EIP6963_REQUEST_EVENT="eip6963:requestProvider";
export const EIP6963_ANNOUNCE_EVENT="eip6963:announceProvider";

export function providerRegistry(){const providers=new Map<string,ProviderDetail>();return {add(detail:ProviderDetail){if(detail?.info?.uuid)providers.set(detail.info.uuid,detail)},remove(uuid:string){providers.delete(uuid)},list(){return [...providers.values()]},get(uuid:string){return providers.get(uuid)}}}
export function createConnectionGate():ConnectionGate{let epoch=0;return{begin(){epoch+=1;return epoch},invalidate(){epoch+=1},isCurrent(token){return token===epoch}}}
export function discoverProviders(target:Window,onProvider:(detail:ProviderDetail)=>void){const handler=(event:Event)=>onProvider((event as CustomEvent<ProviderDetail>).detail);target.addEventListener(EIP6963_ANNOUNCE_EVENT,handler);target.dispatchEvent(new Event(EIP6963_REQUEST_EVENT));return()=>target.removeEventListener(EIP6963_ANNOUNCE_EVENT,handler)}
export function connectionChoice(state:DiscoveryState,providers:ProviderDetail[],fallback?:Eip1193Provider){if(state!=="COMPLETE")return{kind:"discovering" as const};if(providers.length>1)return{kind:"choose" as const};if(providers.length===1)return{kind:"provider" as const,detail:providers[0]};if(fallback)return{kind:"provider" as const,detail:{info:{uuid:"eip1193-fallback",name:"Injected wallet",icon:"",rdns:"fallback"},provider:fallback}};return{kind:"missing" as const}}
export async function ensureBradbury(provider:Eip1193Provider){try{await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:BRADBURY_CHAIN_ID_HEX}]})}catch(error){if(providerCode(error)!==4902)throw error;await provider.request({method:"wallet_addEthereumChain",params:[{chainId:BRADBURY_CHAIN_ID_HEX,chainName:"GenLayer Bradbury",nativeCurrency:{name:"GEN",symbol:"GEN",decimals:18},rpcUrls:[BRADBURY_RPC],blockExplorerUrls:[BRADBURY_EXPLORER]}]});await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:BRADBURY_CHAIN_ID_HEX}]})}const chain=await provider.request({method:"eth_chainId"});if(String(chain).toLowerCase()!==BRADBURY_CHAIN_ID_HEX)throw Object.assign(new Error("Wallet did not switch to GenLayer Bradbury"),{code:"CHAIN_MISMATCH"})}
export async function verifyWriteIdentity(provider:Eip1193Provider,account:string){const chain=await provider.request({method:"eth_chainId"});if(String(chain).toLowerCase()!==BRADBURY_CHAIN_ID_HEX)throw Object.assign(new Error("Network changed before submission"),{code:"CHAIN_MISMATCH"});const accounts=await provider.request({method:"eth_accounts"});if(!Array.isArray(accounts)||typeof accounts[0]!=="string"||accounts[0].toLowerCase()!==account.toLowerCase())throw Object.assign(new Error("Wallet account changed before submission"),{code:"ACCOUNT_MISMATCH"})}
export async function connectWalletCandidate(provider:Eip1193Provider){await ensureBradbury(provider);const raw=await provider.request({method:"eth_requestAccounts"});if(!Array.isArray(raw)||typeof raw[0]!=="string"||!/^0x[a-fA-F0-9]{40}$/.test(raw[0]))throw new Error("Wallet returned no valid account");return raw[0]}
export function bindProviderSession(provider:Eip1193Provider,token:number,gate:ConnectionGate,handlers:{accountsChanged:(account:string|undefined)=>void;chainChanged:()=>void;disconnected:()=>void}){const accounts=(raw:unknown)=>{if(!gate.isCurrent(token))return;const account=Array.isArray(raw)&&typeof raw[0]==="string"&&/^0x[a-fA-F0-9]{40}$/.test(raw[0])?raw[0]:undefined;handlers.accountsChanged(account)};const chain=()=>{if(gate.isCurrent(token))handlers.chainChanged()};const disconnected=()=>{if(gate.isCurrent(token))handlers.disconnected()};const listeners:[[string,(...args:unknown[])=>void],[string,(...args:unknown[])=>void],[string,(...args:unknown[])=>void]]=[["accountsChanged",accounts],["chainChanged",chain],["disconnect",disconnected]];let attached=0;try{for(const [event,handler]of listeners){provider.on?.(event,handler);attached++}}catch{for(let i=0;i<attached;i++){const [event,handler]=listeners[i];try{provider.removeListener?.(event,handler)}catch{/* Hostile provider cleanup is best effort. */}}disconnected();return()=>{}}return()=>{for(const [event,handler]of listeners){try{provider.removeListener?.(event,handler)}catch{/* Hostile provider cleanup is best effort. */}}}}
export function providerCode(error:unknown):string|number|undefined{try{if(error===null||(typeof error!=="object"&&typeof error!=="function"))return undefined;const descriptor=Object.getOwnPropertyDescriptor(error,"code");if(!descriptor||!("value" in descriptor))return undefined;const code=descriptor.value;return typeof code==="string"||typeof code==="number"?code:undefined}catch{return undefined}}
