import { BRADBURY_CHAIN_ID_HEX, BRADBURY_RPC, BRADBURY_EXPLORER } from "./config.ts";

export interface Eip1193Provider { request(args:{method:string;params?:unknown[]}):Promise<unknown>; on?(event:string,handler:(...args:unknown[])=>void):void; removeListener?(event:string,handler:(...args:unknown[])=>void):void }
export type ProviderInfo={uuid:string;name:string;icon:string;rdns:string};
export type ProviderDetail={info:ProviderInfo;provider:Eip1193Provider};
export type DiscoveryState="DISCOVERING"|"COMPLETE";
export type ConnectionGate={begin:()=>number;invalidate:()=>void;isCurrent:(token:number)=>boolean};
export const EIP6963_REQUEST_EVENT="eip6963:requestProvider";
export const EIP6963_ANNOUNCE_EVENT="eip6963:announceProvider";
export type WalletNetworkState="connected"|"changed"|"unavailable";
export type WalletBalanceState={status:"loading"|"available"|"unavailable";value?:string};
export type WalletSnapshot={networkState:WalletNetworkState;balance:WalletBalanceState};
export type SessionEndReason="user"|"switch"|"account"|"provider";
export type WalletAccountSnapshot={account:string;generation:number};
export type WalletAccountGate={set:(account:unknown)=>WalletAccountSnapshot|undefined;clear:()=>void;current:()=>string|undefined;snapshot:()=>WalletAccountSnapshot|undefined;isCurrent:(snapshot:WalletAccountSnapshot)=>boolean};

export function isWalletAddress(value:unknown):value is string{return typeof value==="string"&&/^0x[a-fA-F0-9]{40}$/.test(value)}
export function shortenAddress(address:string,start=6,end=4){return address.length>start+end+1?`${address.slice(0,start)}…${address.slice(-end)}`:address}
export function walletExplorerUrl(explorer:string,address:string){return `${explorer.replace(/\/$/,"")}/address/${address}`}
export function formatNativeBalance(raw:unknown,maximumFractionDigits=4){
 if(typeof raw!=="string"||!/^0x[\da-f]+$/i.test(raw))return undefined;
 const unit=BigInt("1000000000000000000"),wei=BigInt(raw),whole=wei/unit,fraction=(wei%unit).toString().padStart(18,"0").slice(0,maximumFractionDigits).replace(/0+$/,"");
 return `${whole.toLocaleString("en-US")}${fraction?`.${fraction}`:""} GEN`;
}
export function normalizeChainId(raw:unknown){return typeof raw==="string"&&/^0x[\da-f]+$/i.test(raw)?raw.toLowerCase():undefined}
export async function readWalletSnapshot(provider:Eip1193Provider,account:string):Promise<WalletSnapshot>{
 let chain:unknown;try{chain=await provider.request({method:"eth_chainId"})}catch{return{networkState:"unavailable",balance:{status:"unavailable"}}}
 if(normalizeChainId(chain)!==BRADBURY_CHAIN_ID_HEX)return{networkState:"changed",balance:{status:"unavailable"}};
 if(!isWalletAddress(account))return{networkState:"connected",balance:{status:"unavailable"}};
 try{const value=formatNativeBalance(await provider.request({method:"eth_getBalance",params:[account,"latest"]}));return{networkState:"connected",balance:value?{status:"available",value}:{status:"unavailable"}}}catch{return{networkState:"connected",balance:{status:"unavailable"}}}
}
export function safeProviderIcon(value:unknown,maxLength=100_000){if(typeof value!=="string"||value.length<32||value.length>maxLength)return undefined;const match=/^data:image\/(png|jpeg|webp);base64,([a-z\d+/]+={0,2})$/i.exec(value);if(!match||match[2].length%4!==0||typeof globalThis.atob!=="function")return undefined;try{const bytes=globalThis.atob(match[2]);const valid=match[1].toLowerCase()==="png"?bytes.startsWith("\x89PNG\r\n\x1a\n"):match[1].toLowerCase()==="jpeg"?bytes.startsWith("\xff\xd8\xff"):bytes.startsWith("RIFF")&&bytes.slice(8,12)==="WEBP";return valid?value:undefined}catch{return undefined}}
export function providerPresentationName(value:unknown,maxLength=48){if(typeof value!=="string")return"Injected wallet";const name=value.replace(/[\u0000-\u001f\u007f-\u009f]/g,"").trim();return name?name.slice(0,maxLength):"Injected wallet"}
export function walletTriggerLabel(address:string,providerName:string,networkState:WalletNetworkState){const identity=`Wallet connected: ${shortenAddress(address)} using ${providerPresentationName(providerName)}`;return networkState==="connected"?`${identity} on GenLayer Bradbury`:networkState==="changed"?`${identity}; wallet network changed from GenLayer Bradbury`:`${identity}; wallet network status unavailable`}
export function walletNetworkStatusLabel(networkState:WalletNetworkState){return networkState==="connected"?"Connected on Bradbury":networkState==="changed"?"Wallet network changed":"Network status unavailable"}
export function walletRefreshStartBalance(account:unknown):WalletBalanceState{return isWalletAddress(account)?{status:"loading"}:{status:"unavailable"}}
export function disclosureIsOpen(owner:string|undefined,current:string|undefined,requestedOpen:boolean){return Boolean(requestedOpen&&owner&&current&&owner.toLowerCase()===current.toLowerCase())}
export async function copyPublicAddress(address:string,writeText?:((value:string)=>Promise<void>)){if(!/^0x[a-f\d]{40}$/i.test(address)||!writeText)return"unavailable" as const;try{await writeText(address);return"copied" as const}catch{return"unavailable" as const}}
export function sessionEndMessages(reason:SessionEndReason){if(reason==="user")return{status:"Wallet disconnected. Extension permissions were not changed.",error:""};if(reason==="switch")return{status:"Choose a different wallet provider.",error:""};if(reason==="account")return{status:"Wallet disconnected.",error:"The wallet no longer exposes an active account. Reconnect to continue."};return{status:"Wallet provider disconnected.",error:"The selected wallet provider disconnected or disappeared. Reconnect and select an available provider."}}

export function providerRegistry(){const providers=new Map<string,ProviderDetail>();return {add(detail:ProviderDetail){if(detail?.info?.uuid)providers.set(detail.info.uuid,detail)},remove(uuid:string){providers.delete(uuid)},list(){return [...providers.values()]},get(uuid:string){return providers.get(uuid)}}}
export function createConnectionGate():ConnectionGate{let epoch=0;return{begin(){epoch+=1;return epoch},invalidate(){epoch+=1},isCurrent(token){return token===epoch}}}
export function createWalletRefreshGate(){return createConnectionGate()}
export function createWalletAccountGate():WalletAccountGate{let generation=0,account:string|undefined;const snapshot=()=>account?{account,generation}:undefined;return{set(value){if(!isWalletAddress(value))return undefined;generation+=1;account=value;return snapshot()},clear(){generation+=1;account=undefined},current(){return account},snapshot,isCurrent(value){return isWalletAddress(value?.account)&&value.generation===generation&&account!==undefined&&value.account.toLowerCase()===account.toLowerCase()}}}
export function discoverProviders(target:Window,onProvider:(detail:ProviderDetail)=>void){const handler=(event:Event)=>onProvider((event as CustomEvent<ProviderDetail>).detail);target.addEventListener(EIP6963_ANNOUNCE_EVENT,handler);target.dispatchEvent(new Event(EIP6963_REQUEST_EVENT));return()=>target.removeEventListener(EIP6963_ANNOUNCE_EVENT,handler)}
export function connectionChoice(state:DiscoveryState,providers:ProviderDetail[],fallback?:Eip1193Provider){if(state!=="COMPLETE")return{kind:"discovering" as const};if(providers.length>1)return{kind:"choose" as const};if(providers.length===1)return{kind:"provider" as const,detail:providers[0]};if(fallback)return{kind:"provider" as const,detail:{info:{uuid:"eip1193-fallback",name:"Injected wallet",icon:"",rdns:"fallback"},provider:fallback}};return{kind:"missing" as const}}
export async function ensureBradbury(provider:Eip1193Provider){try{await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:BRADBURY_CHAIN_ID_HEX}]})}catch(error){if(providerCode(error)!==4902)throw error;await provider.request({method:"wallet_addEthereumChain",params:[{chainId:BRADBURY_CHAIN_ID_HEX,chainName:"GenLayer Bradbury",nativeCurrency:{name:"GEN",symbol:"GEN",decimals:18},rpcUrls:[BRADBURY_RPC],blockExplorerUrls:[BRADBURY_EXPLORER]}]});await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:BRADBURY_CHAIN_ID_HEX}]})}const chain=await provider.request({method:"eth_chainId"});if(String(chain).toLowerCase()!==BRADBURY_CHAIN_ID_HEX)throw Object.assign(new Error("Wallet did not switch to GenLayer Bradbury"),{code:"CHAIN_MISMATCH"})}
export async function verifyWriteIdentity(provider:Eip1193Provider,account:string){const chain=await provider.request({method:"eth_chainId"});if(String(chain).toLowerCase()!==BRADBURY_CHAIN_ID_HEX)throw Object.assign(new Error("Network changed before submission"),{code:"CHAIN_MISMATCH"});const accounts=await provider.request({method:"eth_accounts"});if(!Array.isArray(accounts)||typeof accounts[0]!=="string"||accounts[0].toLowerCase()!==account.toLowerCase())throw Object.assign(new Error("Wallet account changed before submission"),{code:"ACCOUNT_MISMATCH"})}
export async function connectWalletCandidate(provider:Eip1193Provider){await ensureBradbury(provider);const raw=await provider.request({method:"eth_requestAccounts"});if(!Array.isArray(raw)||typeof raw[0]!=="string"||!/^0x[a-fA-F0-9]{40}$/.test(raw[0]))throw new Error("Wallet returned no valid account");return raw[0]}
export function bindProviderSession(provider:Eip1193Provider,token:number,gate:ConnectionGate,handlers:{accountsChanged:(account:string|undefined)=>void;chainChanged:(chainId:string|undefined)=>void;disconnected:()=>void}){const accounts=(raw:unknown)=>{if(!gate.isCurrent(token))return;const account=Array.isArray(raw)&&typeof raw[0]==="string"&&/^0x[a-fA-F0-9]{40}$/.test(raw[0])?raw[0]:undefined;handlers.accountsChanged(account)};const chain=(raw:unknown)=>{if(gate.isCurrent(token))handlers.chainChanged(normalizeChainId(raw))};const disconnected=()=>{if(gate.isCurrent(token))handlers.disconnected()};const listeners:[[string,(...args:unknown[])=>void],[string,(...args:unknown[])=>void],[string,(...args:unknown[])=>void]]=[["accountsChanged",accounts],["chainChanged",chain],["disconnect",disconnected]];let attached=0;try{for(const [event,handler]of listeners){provider.on?.(event,handler);attached++}}catch{for(let i=0;i<attached;i++){const [event,handler]=listeners[i];try{provider.removeListener?.(event,handler)}catch{/* Hostile provider cleanup is best effort. */}}disconnected();return()=>{}}return()=>{for(const [event,handler]of listeners){try{provider.removeListener?.(event,handler)}catch{/* Hostile provider cleanup is best effort. */}}}}
export function providerCode(error:unknown):string|number|undefined{try{if(error===null||(typeof error!=="object"&&typeof error!=="function"))return undefined;const descriptor=Object.getOwnPropertyDescriptor(error,"code");if(!descriptor||!("value" in descriptor))return undefined;const code=descriptor.value;return typeof code==="string"||typeof code==="number"?code:undefined}catch{return undefined}}
